### ISSUE TITLE
patch routine

### ISSUE THREAD

**Issue by StreetLevel** [JuliaGL/GLVisualize.jl#1]
Hey Simon,

i've played around a little bit with your test-routines on mac OS X and everything seems to be fine!
I think this is a really nice tool.

But i have one question for you:

Could you provide a patch-routine for drawing triangles? Something like MATLAB does with its patch routine. That would be great and would make your program easily applicable for many different tasks.

Greetings max

**Comment by SimonDanisch** [comment]
Hi Max,
there is indirectly a patch routine... You can just define it yourself:
```Julia
using GLVisualize, AbstractGPUArray, GLAbstraction, GeometryTypes, Reactive, ColorTypes, Meshes, MeshIO
 

dirlen 	= 1f0
baselen = 0.02f0
cube 	= GLNormalMesh(Cube(Vec3(1), Vec3(1)))
patch(verts, faces) = visualize(GLNormalMesh(verts, faces))
robj1 = patch(cube.vertices, cube.faces)

push!(GLVisualize.ROOT_SCREEN.renderlist, robj1)
renderloop()
```
Ultimately I want to put functions like patch into GLPlot, as I want to stick to one function name in GLVisualize.

Best,
Simon

**Comment by StreetLevel** [comment]
Hi Simon,

can you give me a short example of how to draw a line from 2 points?

i know this should be simple but somehow it won’t work..

thank you 

max

**Comment by SimonDanisch** [comment]
Admittedly, I don't really do line drawing yet...What have you tried so far that isn't working?
If you can give me some requirements, I can write something up which will draw you some lines ;)

**Comment by StreetLevel** [comment]
This would be really nice!!

With GLPlot something like this worked:


lineshader 	= TemplateProgram(File("./data/line.vert"), File("./data/line.frag"))

## vtxc::Array{GeometryTypes.Point3{Float32},1}
## lnss::Array{Uint32,1}

lines = RenderObject([
			:vertex           => GLBuffer(vtxx), #NOT WORKING
			:index            => indexbuffer(lnss), #NOT WORKING
			:projectionview   => GLVisualize.ROOT_SCREEN.perspectivecam.projectionview
		], lineshader)	
	
prerender!(lines, glEnable, GL_DEPTH_TEST, glDepthFunc, GL_LEQUAL, glDisable, GL_CULL_FACE, enabletransparency)
postrender!(lines, render, lines.vertexarray, GL_LINES)

push!(GLVisualize.ROOT_SCREEN.renderlist, lines)

but with GLVisualize the GLBuffer() gives an error.

I attached an file with some example data.

Greetings Max

**Comment by SimonDanisch** [comment]
I added an example where it works ;)
I deprecated `{{out}}`/ `{{in}}`, so that you can now just write `out`/`in`.. Also `std_renderobject` adds the most common prerender/postrender commands... Input(lineshader) is just a quick work around for an API inconsistency, which I didn't notice so far...

**Comment by StreetLevel** [comment]
Hey Simon,

Perfekt, that ist working. Many thanks!!!
