### ISSUE TITLE
First to comment - last merge to master

### ISSUE THREAD

**Issue by hustf** [JuliaGL/GLVisualize.jl#106]
Checked out today's big merge. I am really just being curious to see if text labels are included and working now. 
Current check out list to master:
Reactive
GLVisualize
GLAbstraction
GeometryTypes
GLWindow
Reactive
GLVisualize

```
julia> Pkg.test("GLVisualize")
INFO: Computing test dependencies for GLVisualize...
INFO: No packages to install, update or remove
INFO: Testing GLVisualize
pwd() = locJPathC:\users\f\j
Suggest cd(workPath), workPath= C:\users\f\j\WebCat\src
INFO: Recompiling stale cache file C:\Users\F\.julia\lib\v0.4\GLVisualize.ji for module GLVisualize.
WARNING: Base.String is deprecated, use AbstractString instead.
  likely near C:\Users\F\.julia\v0.4\GLVisualize\src\FreeTypeAbstraction.jl:19
WARNING: Base.String is deprecated, use AbstractString instead.
  likely near C:\Users\F\.julia\v0.4\GLVisualize\src\FreeTypeAbstraction.jl:19
ERROR: LoadError: UndefVarError: similar_type not defined
 in gl_convert at C:\Users\F\.julia\v0.4\GLAbstraction\src\GLUniforms.jl:212
 in call at C:\Users\F\.julia\v0.4\GLAbstraction\src\GLTypes.jl:228
 in instanced_renderobject at C:\Users\F\.julia\v0.4\GLAbstraction\src\GLRenderObject.jl:60
 in assemble_shader at C:\Users\F\.julia\v0.4\GLVisualize\src\utils.jl:26
 in visualize at C:\Users\F\.julia\v0.4\GLVisualize\src\visualize_interface.jl:20
 in anonymous at no file
 in include at boot.jl:261
 in include_from_node1 at loading.jl:320
 in process_options at client.jl:280
 in _start at client.jl:378
while loading C:\Users\F\.julia\v0.4\GLVisualize\test\runtests.jl, in expression starting on line 63
=====================================[ ERROR: GLVisualize ]=====================================

failed process: Process(`'C:\Users\F\AppData\Local\Julia-0.4.6\bin\julia' --check-bounds=yes --code-coverage=none --color=yes 'C:\Users\F\.julia\v0.4\GLVisualize\test\runtests.jl'`, ProcessExited(1)) [1]

================================================================================================
INFO: No packages to install, update or remove
ERROR: GLVisualize had test errors
 in error at error.jl:21
```

**Comment by SimonDanisch** [comment]
You need to add `FixedSizeArrays` to that list  ;)
So far, it's only testet on 0.5, though!

**Comment by hustf** [comment]
I thought so perhaps. FixedSizeArrays used to be pinned to pinned.b8d3d5ec.tmp before this test. Checking out master now.

**Comment by SimonDanisch** [comment]
That explains it, since the newest tagged version should also work ;)

**Comment by hustf** [comment]
Nah, I was unclear. I used the tagged version when running the above.

**Comment by hustf** [comment]
Mind boggling. The window stays open, and does not crash when closed. 
No text in the test so far. Is that related to you not changing to AbstractString yet perhaps?

![capture](https://cloud.githubusercontent.com/assets/13949620/17530172/b9a06754-5e76-11e6-81cd-1dee32879b62.JPG)

**Comment by SimonDanisch** [comment]
No... You can checkout `examples/text/text.jl` for that ;)
Text editing is still not working, but I'm on it (soon) :D

**Comment by hustf** [comment]
Excellent. It works. I hope I'm better qualified to understand how this whole thing works now than at my last tries.  I took a fork and simply changed a String to AbstractString. at line 20. That seemed to work. I'm trying my luck to see if I can get this PR accepted, I think.
