### ISSUE TITLE
MeshesIO example not working on julia v0.4.6

### ISSUE THREAD

**Issue by abieler** [JuliaGL/GLVisualize.jl#109]
I just tried to do the MeshesIO example from the docs (with another .obj file though) in a notebook:
http://www.glvisualize.com/examples/meshes/#meshes-io

```julia
using GLVisualize, GeometryTypes, GLAbstraction, Colors, FileIO

window = glscreen()

# loadasset is defined as `loadasset(name) = load(assetphat(name))`
# load comes from FileIO, which automatically detects the file format and loads it
# in general, load will try to load the mesh as is, which may return different
# meshtypes. This is why it's wrapped into GLNormalMesh, to guarantee some type
# stability.
# Formats supported are currently: obj, stl, ply, off and 2DM
msh = GLNormalMesh(loadasset("cat.obj"))

view(visualize(msh), window)

renderloop(window)
```

but it failed with the following message:

**LoadError: UndefVarError: view not defined
while loading In[1], in expression starting on line 14**

I am on v0.4.6 linux.

```julia
Pkg.test("GLVisulaize")
```
passes and I did the whole list of:

```julia
Pkg.checkout("GLVisualize")
Pkg.checkout("GLAbstraction")
Pkg.checkout("GeometryTypes")
Pkg.checkout("GLWindow")
Pkg.checkout("Reactive")
```

Something I am missing?
Thanks
Andre

**Comment by SimonDanisch** [comment]
Sorry, i can't use view anymore because of clashes with Base.view... So I
adhock fixed it by renaming it to `_view` ... Not beautiful, but i'm still
undecided on the final name!

**Comment by abieler** [comment]
That works! Thanks!
