### ISSUE TITLE
#surface example doesn't animate after restart

### ISSUE THREAD

**Issue by crunch3** [JuliaGL/GLVisualize.jl#110]
http://www.glvisualize.com/examples/surfaces/#surface animates fine upon a fresh load, but after closing that window, a second instance in the same session does not animate.

Sometimes after several attempts, you get an out of memory error and the Julia shell crashes.

This is on a 32GB Windows-10 machine with roughly 16GB of free memory.

**Comment by SimonDanisch** [comment]
That sounds terrible! :D What version of `GLVisualize` are you on?
The one you get when you only do `Pkg.add("GLVisualize")` ?

**Comment by crunch3** [comment]
Latest version (0.0.10).  I have Pkg.update() in my startup script.

**Comment by SimonDanisch** [comment]
Can you try:
```Julia
for p in ["GLVisualize", "GeometryTypes", "GLAbstraction", "GLWindow", "FixedSizeArrays"]
    Pkg.checkout(p)
end
```
At least the animation part should be fixed there!
I sometimes get a segfault when closing and reopening the window a lot. Maybe they're related and just express themselves differently? Is it the Julia `OutOfMemoryError()`? Or could it come from some C-library, or even refer to gpu memory?

**Comment by SimonDanisch** [comment]
The example code needs to be slightly different though:
https://github.com/JuliaGL/GLVisualize.jl/blob/master/examples/surfaces/surface.jl

**Comment by hustf** [comment]
Simon, I got an error when running that example code straight after recompiling. Something about trying to access the zero element in a tuple, at line 22:

view(visualize(const_lift(surf, t, 400), :surface, boundingbox=bb))

At my second try, the example seems to work fine. Julia use 313Mb of memory with the window open.

I have a complicated mix of checked out and dirty referred packages. GLVisualize on the same version as crunch3. Windows 10.

**Comment by SimonDanisch** [comment]
Should be fixed on master!
