### ISSUE TITLE
Checkout master errors

### ISSUE THREAD

**Issue by joa-quim** [JuliaGL/GLVisualize.jl#112]
Simon,

On a fresh install of Julia 0.5 (note, I had done a `Pkg.add("GLVisualize")` before and it worked fine)
(Win10)

```
julia> Pkg.checkout("GLVisualize")
INFO: Checking out GLVisualize master...
INFO: Pulling GLVisualize latest master...
ERROR: stat: operation not permitted (EPERM)
 in stat(::String) at .\stat.jl:69
 in isdir at .\stat.jl:135 [inlined]
 in isinstalled(::String) at .\pkg\read.jl:55
 in installed(::Dict{String,Dict{VersionNumber,Base.Pkg.Types.Available}}) at .\pkg\read.jl:204
 in resolve at .\pkg\entry.jl:476 [inlined] (repeats 3 times)
 in (::Base.Pkg.Entry.##18#20{String,String,Bool,Bool})(::Base.LibGit2.GitRepo) at .\pkg\entry.jl:237
 in transact(::Base.Pkg.Entry.##18#20{String,String,Bool,Bool}, ::Base.LibGit2.GitRepo) at .\libgit2\libgit2.jl:520
 in with(::Base.Pkg.Entry.##17#19{String,String,Bool,Bool}, ::Base.LibGit2.GitRepo) at .\libgit2\types.jl:638
 in checkout(::String, ::String, ::Bool, ::Bool) at .\pkg\entry.jl:227
 in (::Base.Pkg.Dir.##2#3{Array{Any,1},Base.Pkg.Entry.#checkout,Tuple{String,String,Bool,Bool}})() at .\pkg\dir.jl:31
 in cd(::Base.Pkg.Dir.##2#3{Array{Any,1},Base.Pkg.Entry.#checkout,Tuple{String,String,Bool,Bool}}, ::String) at .\file.jl:48
 in #cd#1(::Array{Any,1}, ::Function, ::Function, ::String, ::Vararg{Any,N}) at .\pkg\dir.jl:31
 in checkout(::String) at .\pkg\pkg.jl:170
```

Also, in another machine where I already had the master version and after `Pkg.update()`, it now

```
julia> using GLVisualize
INFO: Precompiling module GLVisualize.
ERROR: LoadError: LoadError: UndefVarError: robj_from_camera not defined
 in include_from_node1(::String) at .\loading.jl:488 (repeats 2 times)
 in macro expansion; at .\none:2 [inlined]
 in anonymous at .\<missing>:?
 in eval(::Module, ::Any) at .\boot.jl:234
 in process_options(::Base.JLOptions) at .\client.jl:239
 in _start() at .\client.jl:318
while loading C:\j\.julia\v0.5\GLWindow\src\screen.jl, in expression starting on line 385
while loading C:\j\.julia\v0.5\GLWindow\src\GLWindow.jl, in expression starting on line 29
```

**Comment by SimonDanisch** [comment]
>ERROR: stat: operation not permitted (EPERM)

That seems to be a Pkg/LibGit error?

Note, that if you checkout GLVisualize, you also need to checkout:
```Julia
    for pkg in [
            "GLWindow", "GLAbstraction",
            "GLVisualize", "GeometryTypes", "FixedSizeArrays",
            "FreeType", "GLPlot"
        ]
        Pkg.checkout(pkg)
end
```

>after Pkg.update(), it now:

Either you accidentally checked out one of the packages, or I've tagged the wrong packages. But I'm pretty sure, that the current tags are quite old and relatively well tested.
Can you post the result of `Pkg.status()`?

Well, I should be tagging a new version very soon anyways!

**Comment by joa-quim** [comment]
The LibGit error seamed to have gone. On a second attempt it did not complain anymore. And after checking out ``FixedSizeArrays`` and ``FreeType`` (which are not listed as mandatory in the GLVisualize page) than ``Pkg.test("GLVisualize")`` run fine in the fresh install machine.

Also, on the other machine some of those packages were not on master (!!!!). Don't know why because I would swear I had checked out master versions. It now also works there.

Thanks.

BTW, have you seen [this](https://github.com/JuliaGL/GLVisualize.jl/issues/82#issuecomment-247983635)?
I found out to plot it with Pyplot but that's not exactly what I was looking for (too Matlabish in figure space wasting)

**Comment by SimonDanisch** [comment]
yeah I have... Sorry, I'm working on a deadline right now, so I had to drop a lot of unfinished business!
I'll still try to see how far I can get to tag everything!

>(too Matlabish in figure space wasting)

What do you mean by that? The image not fully filling out the canvas?

**Comment by joa-quim** [comment]
Yes, too much gray space wasted.
And take your time, no hurry here (many other things to do too).

**Comment by SimonDanisch** [comment]
Newest version is tagged now! So it should work now.
