### ISSUE TITLE
Slow load time 

### ISSUE THREAD

**Issue by musm** [JuliaGL/GLVisualize.jl#113]
On my computer it takes a couple of seconds (1-3) to load of the first plot pane, which is very slow.

**Comment by SimonDanisch** [comment]
Yeah I'm not at all happy with that. Static compilation and caching fonts will be the way forward! Which already kinda exist, I just need to see how to ship it best!

**Comment by musm** [comment]
Static compilation, care to explain how that would work?  So the precompilation isn't able to compile enough functions?

**Comment by SimonDanisch** [comment]
>So the precompilation isn't able to compile enough functions?

Yup! So precompilation basically just caches the lowered (type inferred?) form, as far as I know.
The most expensive pass is the pass to generate native code, which doesn't happen for precompilation.
Easiest fix is to put the library into the system image, best combined with SnoopCompile, to figure out the argument types of all used functions:
https://github.com/JuliaGL/GLVisualize.jl/blob/master/precompile/userimg_glvisualize.jl

**Comment by musm** [comment]
Very interesting, I'll have to try that and see how much faster everything is, thanks.

**Comment by SimonDanisch** [comment]
Okay! If you give me some time, I can make sure that the precompile file is up to date... That was on my schedule for today anyways ;)

**Comment by musm** [comment]
https://github.com/JuliaGL/GLVisualize.jl/blob/master/precompile/userimg_glvisualize.jl#L30

use: `include(joinpath(dirname(JULIA_HOME),"share","julia","build_sysimg.jl")) `

**Comment by SimonDanisch** [comment]
I haven't been able to get precompile working :( There where some weird missing methods errors after putting it in the system image, and after sort of fixing them, I didn't get any compile speed improvements.
I'll continue investigating! 
On the bright side: I implemented font caching, which shaved off something like 30 seconds from start to first plot needing fonts :)
It's not merged yet, but will do so soon!

**Comment by timholy** [comment]
In an ideal world one could leave a julia session open for a week and the compilation time would be amortized. 0.6 is a bit better in this regard because the infamous 265 is fixed, but I find I still restart frequently so it doesn't quite work out.
