### ISSUE TITLE
Plotting many points

### ISSUE THREAD

**Issue by musm** [JuliaGL/GLVisualize.jl#114]
Using Plots.jl

`plot(randn(1000000,1))` is extremely slow to zoom and interact.
The same thing in matlab is fast and I can freely zoom and move the plot around with little lag.

Matlab may be doing some adaptive resolution work here, thougth I'm not sure.

**Comment by SimonDanisch** [comment]
Do the lines look fully smooth in Matlab? A speedy, non anti aliased version should be quite a bit faster than what I currently have.
I also could try culling and things like that ;)

**Comment by musm** [comment]
Yes they look smooth. I'll try to take a picture when I'm on my main machine. It looks like they cull data and as you zoom in things refine, fyi.

**Comment by SimonDanisch** [comment]
Okay... So for a first step, I've implemented the ugly lines and they can display this amount of data without a problem. @tbreloff, now it would be the question, how we can say in Plots.jl: display the lines quick and ugly!

**Comment by tbreloff** [comment]
Hmm. Maybe we could have a plot attribute that conveys output needs, like
"output = :fast". I'm open to suggestions.

**Comment by SimonDanisch** [comment]
Kind of fixed by 1b23097
