### ISSUE TITLE
groupedbar plot doesn't plot nicely

### ISSUE THREAD

**Issue by musm** [JuliaGL/GLVisualize.jl#115]
julia> using StatPlots
julia>glvisualize()
julia> groupedbar(["Half","Full","Double"], rand(3,2), w=0, lab=["OJ" "Vit C"], xguide="Dose",yguide="Length",title="Grouped Bar Chart")

![image](https://cloud.githubusercontent.com/assets/4319522/19094759/d8b2b07e-8a5f-11e6-92f5-f28b84cbc5d2.png)

**Comment by musm** [comment]
`set_theme(:ggplot2)` also doesn't seem to work properly.

**Comment by SimonDanisch** [comment]
Sorry completely missed this issue somehow! This needs fixing! It's a Plots.jl backend issue though ;)

**Comment by musm** [comment]
ah ok, shall I report upstream to Plots.jl then?

**Comment by SimonDanisch** [comment]
If you wish ;) I'd still be the one fixing it though, so not really needed!
