### ISSUE TITLE
Unable to use glscreen() on mac

### ISSUE THREAD

**Issue by leios** [JuliaGL/GLVisualize.jl#116]
Hey,

I am using an imac OSX version 10.11.6 with AMD Radeon R9 M380 2048 MB. Let me know if you need further details.

I have added the GLVisualize Package with Pkg.add("GLVisualize") and have precompiled the package just fine; however, glscreen() provides the following error:

```julia
glscreen()
ERROR: error compiling __create_glcontext#2__: error compiling glDebugMessageCallbackARB: error compiling getprocaddress_e: error compiling getprocaddress: could not load library "opengl32"
dlopen(opengl32.dylib, 1): image not found
 in Screen at /Users/james/.julia/v0.4/GLWindow/src/screen.jl:240
 in glscreen at /Users/james/.julia/v0.4/GLVisualize/src/renderloop.jl:10
```

I then tried to checkout the GLVisualize package and after rebuilding, I receive the following error on precompiling:

```julia
using GLVisualize
INFO: Precompiling module GLVisualize...
ERROR: LoadError: LoadError: syntax: invalid "::" syntax
 in include at /opt/local/lib/julia/sys.dylib
 in include_from_node1 at /opt/local/lib/julia/sys.dylib
 in include at /opt/local/lib/julia/sys.dylib
 in include_from_node1 at /opt/local/lib/julia/sys.dylib
 in process_options at /opt/local/lib/julia/sys.dylib
 in _start at /opt/local/lib/julia/sys.dylib
while loading /Users/james/.julia/v0.4/GLVisualize/src/types.jl, in expression starting on line 202
while loading /Users/james/.julia/v0.4/GLVisualize/src/GLVisualize.jl, in expression starting on line 66
ERROR: Failed to precompile GLVisualize to /Users/james/.julia/lib/v0.4/GLVisualize.ji
 in error at /opt/local/lib/julia/sys.dylib
 in compilecache at ./loading.jl:400
 in require at /opt/local/lib/julia/sys.dylib
```

Neither of these errors occur on my linux-box, so I feel I may have missed something along the way for mac.

Thanks,
James

**Comment by SimonDanisch** [comment]
Hi,
sorry for the hassle.
I just opened a PR at ModernGL to fix your first error:
https://github.com/JuliaGL/ModernGL.jl/pull/32

The second error is due to some 0.5 syntax I started using and I haven't tested master on 0.4 yet.
I've fixed it in: c688de27f4fdef088eeb9d5ed4e11081dc62a83a

Note that you need to checkout more then just GLVisualize to work on master:
```Julia
Pkg.checkout("GLVisualize")
Pkg.checkout("GLAbstraction")
Pkg.checkout("GLWindow")
Pkg.test("GLVisualize")
```

Best,
Simon

**Comment by leios** [comment]
Hey Simon,

Thanks for being so quick with this. Great work so far! 

James

**Comment by SimonDanisch** [comment]
Sure! Thanks for finding these! :)
