### ISSUE TITLE
FXAA antialiasing needed to make 3d graphics smooth

### ISSUE THREAD

**Issue by musm** [JuliaGL/GLVisualize.jl#118]
Without forcing FXAA antialiasing on my nvidia gpu, the 3d graphics output from GLVisualize are very jagged (2D graphics are smooth).

**Comment by SimonDanisch** [comment]
True. I've had FXAA on another branch... Let me see how complicated it would be to make it available on master!

**Comment by SimonDanisch** [comment]
Done! Text looks uglier though.. So I either neee to seperate the passes or allow to turn it off

**Comment by musm** [comment]
which branch is this on?

**Comment by SimonDanisch** [comment]
It's on `GLWindow sd/fxaa`... Should work with GLVisualize master, not thoroughly tested though :P I try to get it merged today

**Comment by SimonDanisch** [comment]
This is on master now!
