### ISSUE TITLE
Animating mesh

### ISSUE THREAD

**Issue by RoryTN** [JuliaGL/GLVisualize.jl#121]
Hi

Thanks for the library.
I am trying to visualise some depth camera video data.
I've managed to generate an animated surface relatively easily that updates the surface height data with every frame. However I wanted to render only a sub set of the faces and have specific per vertex colours so I tried making use of a vertex colour mesh instead.
I hoped simply passing a  `Signal{GLNormalVertexcolorMesh}` to `visualise` would work however while `visualise` accepts it, it only seems to render the first value and not the following updates even though they are still calculated in the background.
I see all the mesh examples use static vertex data. I tried animating the vertex color mesh example as follows.
```
using GLVisualize, GeometryTypes, GLAbstraction, Colors

window = glscreen()
timesignal = loop(linspace(0f0,1f0,20))

sphere_mesh = map(timesignal) do t
    # one could also create a GLNormalAttributeMesh manually:
    sphere = Sphere{Float32}(Point3f0(0), 1.0 + 20*t)
    # decompose decomposes a mesh or geometry into the primitive of the first argument
    vertices = decompose(Point3f0, sphere, 50)
    faces = decompose(GLTriangle, sphere, 50)
    # create some colors for each vertex, must be Float32
    colors = RGBA{Float32}[RGBA{Float32}(rand(), rand(), rand(), 1.) for i=1:length(vertices)]
    GLNormalVertexcolorMesh(
        vertices=vertices, faces=faces,
        color=colors)
end

view(visualize(sphere_mesh), window)
renderloop(window)
```
And alas, it only renders the first frame.
Is there any plan to support such mesh animation, or am I going about this the wrong way and there's another way to animate mesh vertex data?

Thanks

**Comment by SimonDanisch** [comment]
This is something I've recently made work :)
I'm about to tag the newest version!
If you already want to try it out, please check out the new version like this:
```Julia
Pkg.update() # just to make sure everything is up to date
Pkg.add("GLVisualize")
Pkg.checkout("SignedDistanceFields")
Pkg.checkout("GLAbstraction")
Pkg.checkout("GLWindow")
Pkg.checkout("GLVisualize")
# Optional, but adds cool examples:
Pkg.add("Plots")
Pkg.checkout("Plots", "dev")
```
Note, that `view` temporarily got renamed to `_view` because of clashes with Base.
Enjoy the new interactive runtest with: `Pkg.test("GLVisualize")`

**Comment by RoryTN** [comment]
Thanks, works like a charm.

**Comment by SimonDanisch** [comment]
great :)
