### ISSUE TITLE
tests not showing properly

### ISSUE THREAD

**Issue by musm** [JuliaGL/GLVisualize.jl#123]
![image](https://cloud.githubusercontent.com/assets/4319522/20296951/dfd037b8-aadb-11e6-8a24-6f1fd753eec5.png)

I don't think I have to say more, but yeah things are cutoff not sized correctly (master)

**Comment by SimonDanisch** [comment]
This looks like windows, so I'm guessing it will be using ImageMagick to load the icons?
Lol, this seems almost like ImageMagick wants to mock me... 
How the hell is it possible, that it simply loads the icons rotated, even though that I'm testing on the same OS with the same library, with the same images...
Can you give me some more informations about OS, ImageMagick version, Julia version etc?

**Comment by musm** [comment]
oh wait,

this might be related to the large refactor to fixed-renaming ?
```
 - FixedPointNumbers             0.2.1+             teh/compact_printing
 - FixedSizeArrays               0.2.4+             master
 - FreeType                      1.1.0              master
 - GLAbstraction                 0.1.0+             master
 - GLPlot                        0.0.5+             master
 - GLVisualize                   0.0.10+            master
 - GLWindow                      0.1.4+             master

 - ImageMagick                   0.1.8+             fixed-renaming   
 - ImageView                     0.2.0+             fixed-renaming   
 - Images                        0.5.10+            fixed-renaming   
```

**Comment by musm** [comment]
I had to use those branches because of many other problems with  images not working etc... tholy wrote a gist to checkout the right magical combination of image related packages to make things work, but I guess they don't interact well with glvisualize ....

**Comment by SimonDanisch** [comment]
Okay, that doesn't sound too unlikely... Maybe he actually fixed something. When I remember it correctly I started working around some orientation issue, which might have been wrong behavior!

**Comment by timholy** [comment]
Yes, one of the major goals of the Images rewrite was to fix the orientation issues. `Image` as a dictionary is now unnecessary except for cases where you need extra metadata---all the orientation is handled by the type system. Indeed, it's now simply that the first dimension is vertical. However, note that's not necessarily the same as the fast dimension because we now have lazy permutations with `permuteddimsview` (which is a big part of what makes this rewrite possible).

**Comment by timholy** [comment]
Note that these branches haven't been merged yet...I'm waiting for a few real-world test reports first. If I never get any, I'll merge anyway once I convert my lab's code over to julia 0.5/new Images, but there are still a few pretty big changes in front of this (e.g., https://github.com/JuliaOpt/Optim.jl/pull/303).

**Comment by SimonDanisch** [comment]
Great! Thanks for confirming! @musm, so fixing this will not be an immediate priority before release, but I will create a branch for this as quickly as possible!
