### ISSUE TITLE
UnicodeFun is required while requiring itself julia 0.5

### ISSUE THREAD

**Issue by fp4code** [JuliaGL/GLVisualize.jl#125]
There is a problem with julia-0.4 since UnicodeFun was added to REQUIRE because UnicodeFun/REQUIRE contains "julia 0.5"

**Comment by SimonDanisch** [comment]
Sorry, I've been using GLVisualize exclusively on 0.5.
I will test GLVisualize on 0.4 tomorrow!

**Comment by SimonDanisch** [comment]
Done! See merged PR's and:
https://github.com/SimonDanisch/UnicodeFun.jl/pull/5
