### ISSUE TITLE
GLFW on OSX

### ISSUE THREAD

**Issue by zahachtah** [JuliaGL/GLVisualize.jl#134]
I saw the other issue with GLFW but seems this is different?

when Pkg.add("GLVisualize") I get the error below, also if I try Pkg.checkout("GLFW") and then build.

Any suggestions? GLVisualize is addictive.....I need it :-)

Warning: Use glfw instead of deprecated homebrew/versions/glfw3
================================[ ERROR: GLFW ]=================================

LoadError: SystemError: opening file /Users/jonnorberg/.julia/v0.5/Homebrew/deps/usr/Library/Taps/homebrew/homebrew-versions/glfw3.rb: No such file or directory
while loading /Users/jonnorberg/.julia/v0.5/GLFW/deps/build.jl, in expression starting on line 52

================================================================================

================================[ BUILD ERRORS ]================================

WARNING: GLFW had build errors.

 - packages with build errors remain installed in /Users/jonnorberg/.julia/v0.5
 - build the package(s) and all dependencies with `Pkg.build("GLFW")`
 - build a single package by running its `deps/build.jl` script

**Comment by SimonDanisch** [comment]
I'm not really sure about OSX and homebrew. I know some issues could be fixed by `Pkg.update("Homebrew")`.
@jayschwa, any ideas?

**Comment by jayschwa** [comment]
It looks like Homebrew moved the GLFW formula out of https://github.com/Homebrew/homebrew-versions and into https://github.com/Homebrew/homebrew-core. Thanks for the heads up, I will have a fix out shortly!

**Comment by SimonDanisch** [comment]
Thanks a lot! :)

**Comment by SimonDanisch** [comment]
closing in favor of https://github.com/JuliaGL/GLFW.jl/pull/97
