### ISSUE TITLE
2D view of 3D surface

### ISSUE THREAD

**Issue by edljk** [JuliaGL/GLVisualize.jl#140]
What is the simplest way to obtain a centred 2D view of a 3D surface from above (let say from the position (0,0,1)) ? I have difficulties to adjust camera parameters/mode of the following example. Thanks !

```julia
using GLVisualize, GLAbstraction, GeometryTypes, Reactive, Colors
dphi, dtheta = π/250.0, π/250.0
phi, theta = meshgrid(collect(0:dphi:π+dphi*1.5),collect(0:dtheta:2*π+dtheta*1.5))
m0 = 4; m1 = 3; m2 = 2; m3 = 3; m4 = 6; m5 = 2; m6 = 6; m7 = 4;
r = sin(m0*phi).^m1 + cos(m2*phi).^m3 + sin(m4*theta).^m5 + cos(m6*theta).^m7
x = r.*sin(phi).*cos(theta); y = r.*cos(phi); z = r.*sin(phi).*sin(theta)
x = convert(Array{Float32,2},x); y = convert(Array{Float32,2},y)
z = convert(Array{Float32,2},z)
window = glscreen(resolution=(800,600),color=RGBA(0.7,0.7,0.7,1))
surface = visualize((x,y,z),:surface)
_view(surface, window)
@async renderloop(window)
```

**Comment by SimonDanisch** [comment]
Would it be okay to adjust it interactively? Because then GLPlot would be the easiest option!
It offers steerings to lock onto an axis and switch to orthographic projection for exactly that purpose:
![drawing](https://cloud.githubusercontent.com/assets/1010467/22864815/063173a0-f126-11e6-8aa0-bbd4bac10c56.jpeg)

Make sure to checkout master, until this gets merged: https://github.com/JuliaLang/METADATA.jl/pull/7696

**Comment by edljk** [comment]
Using GLPlot interactively would be perfect !
Which instructions exactly produced your very nice illustration ?
Thanks a lot !

**Comment by SimonDanisch** [comment]
I hoped the button in the pictures are self explanatory ;)
The upper one is a cube to lock to different sides, the lower one can switch between perspective and orthographic projection.

**Comment by edljk** [comment]
Oups, sorry. I never used GLPlot. Nice and simple :

```julia
using GLVisualize, GLAbstraction, GeometryTypes, Reactive, Colors, GLPlot
...
GLPlot.init()
obj = glplot((x, y, z), :surface)
```
Thanks a lot !

**Comment by edljk** [comment]
Always more complicated :-). I tried to use GLPlot for several scenes. I simply switched the window initialization in the example file  "GLVisualize/examples/introduction/screens.jl":

```julia
using GLVisualize, Reactive, GeometryTypes, GLWindow, GLAbstraction, Colors, GLPlot
window = GLPlot.init()
...
```

The three scenes are displayed but the controls butons seem to be lost. Is there an other way to display multiple scenes with GLPlot ? I understood that multiple windows would be more tricky ? Thanks.

**Comment by SimonDanisch** [comment]
Sorry for the late reply.
Yeah this is a UI problem and I need to decide what the default would be.
Maybe the easiest would be to just export a function, that can add these controls to any screen and by default only the GLPlot main screen has these.

**Comment by edljk** [comment]
There is no emergency. Yes adding the controls on demand could be a nice option. 
Adding a resolution control to GLPlot.init() could also be nice (far simpler :-)).
Thank you for all you work !

**Comment by edljk** [comment]
I tried a very naive approach by just modifying the beginning of GLPlot.init():
```julia
function init(w::GLWindow.Screen=glscreen("GLPlot");
              resolution::Tuple{Int64,Int64}=GLWindow.standard_screen_resolution())
    #=if !isempty(plotting_screens) && isopen(first(plotting_screens))
        return # already initialized
      end
    empty!(plotting_screens)
    w = glscreen("GLPlot",resolution=resolution)=#
...
``` 
Thus the following example produces the expected effects but additional black flashes appears.. Any idea ?

```julia
using GLVisualize, Reactive, GeometryTypes, GLWindow, GLAbstraction, Colors, GLPlot

window = glscreen(string("Test multiple Gplot screens"),resolution=(700,500))
texta, viewa = y_partition(window.area, 0)
view1da, view2da = x_partition(window.area,50)
viewscreen = Screen(window,name=:viewscreen,area = viewa)

debugging = true; clear = true;  hidden = false; visible = true
screen3D1 = GLPlot.init(Screen(viewscreen,name=:screen3D1,area=view1da,clear=clear,hidden=hidden))
screen3D1.color = RGBA(0.7,0.7,0.7,1)
screen3D2 = GLPlot.init(Screen(viewscreen,name=:screen3D2,area=view2da,clear=clear,hidden=hidden))
screen3D2.color = RGBA(0.9,0.9,0.9,1)

# plots
msh = GLNormalMesh(loadasset("cat.obj"))
println(msh)
_view(visualize(msh,color=RGBA{Float32}(0.8,rand()/3,rand()/3)),screen3D1)
_view(visualize(msh,color=RGBA{Float32}(rand()/3,0.8,rand()/3)),screen3D2)
@async renderloop(window)
```
![cats](https://cloud.githubusercontent.com/assets/14992507/23024192/4e084574-f459-11e6-90f0-5fa17a03d730.png)

**Comment by SimonDanisch** [comment]
I'm guessing you have multiple render loops. You only need one for the root window!
(this is the GLPlot one: https://github.com/SimonDanisch/GLPlot.jl/blob/master/src/screen.jl#L51, which will get called in `GLPlot.init`)

**Comment by edljk** [comment]
Great : I simply commented the render line at the end of GLPlot.init and the example works like a charm.

```julia
#global _renderloop_task = @async glplot_renderloop(w, compute_sig, record_sig)
```
 Of course the recording capability has been  disabled but I do not know how to make it work... Sorry for the naivety of the approach.

**Comment by SimonDanisch** [comment]
No worries, it's nice to see someone hacking around with it :)
The recording is kind of broken anyways right now...
I switched to the new fast stream based saving of frames. I tested that with GLVisualize on another PC where it works. So either it doesn't work on the new PC, or it somehow doesn't work with GLPlot (which would be slightly weird).
