### ISSUE TITLE
Error When Testing on Ubuntu

### ISSUE THREAD

**Issue by ERPPC** [JuliaGL/GLVisualize.jl#147]
I'm getting the following error when installing and running the test in Ubuntu. 

julia> Pkg.test("GLVisualize")
INFO: Computing test dependencies for GLVisualize...
INFO: Installing Contour v0.2.0
INFO: Installing DocStringExtensions v0.3.1
INFO: Installing Highlights v0.2.1
INFO: Installing ImageMagick v0.2.2
INFO: Building ImageMagick
INFO: Testing GLVisualize
LLVM ERROR: Inline asm not supported by this streamer because we don't have an asm parser for this target

======================================[ ERROR: GLVisualize ]======================================

failed process: Process(`/home/nathan/Documents/julia-3c9d75391c/bin/julia -Cx86-64 -J/home/nathan/Documents/julia-3c9d75391c/lib/julia/sys.so --compile=yes --depwarn=yes --check-bounds=yes --code-coverage=none --color=yes --compilecache=yes /home/nathan/.julia/v0.5/GLVisualize/test/runtests.jl`, ProcessExited(1)) [1]

==================================================================================================
INFO: Removing Contour v0.2.0
INFO: Removing DocStringExtensions v0.3.1
INFO: Removing Highlights v0.2.1
INFO: Removing ImageMagick v0.2.2
ERROR: GLVisualize had test errors
 in #test#61(::Bool, ::Function, ::Array{AbstractString,1}) at ./pkg/entry.jl:740
 in (::Base.Pkg.Entry.#kw##test)(::Array{Any,1}, ::Base.Pkg.Entry.#test, ::Array{AbstractString,1}) at ./<missing>:0
 in (::Base.Pkg.Dir.##2#3{Array{Any,1},Base.Pkg.Entry.#test,Tuple{Array{AbstractString,1}}})() at ./pkg/dir.jl:31
 in cd(::Base.Pkg.Dir.##2#3{Array{Any,1},Base.Pkg.Entry.#test,Tuple{Array{AbstractString,1}}}, ::String) at ./file.jl:59
 in #cd#1(::Array{Any,1}, ::Function, ::Function, ::Array{AbstractString,1}, ::Vararg{Array{AbstractString,1},N}) at ./pkg/dir.jl:31
 in (::Base.Pkg.Dir.#kw##cd)(::Array{Any,1}, ::Base.Pkg.Dir.#cd, ::Function, ::Array{AbstractString,1}, ::Vararg{Array{AbstractString,1},N}) at ./<missing>:0
 in #test#3(::Bool, ::Function, ::String, ::Vararg{String,N}) at ./pkg/pkg.jl:258
 in test(::String, ::Vararg{String,N}) at ./pkg/pkg.jl:258

nathan@CodeBot:~$ glxinfo | grep version
server glx version string: 1.4
client glx version string: 1.4
GLX version: 1.4
    Max core profile version: 3.3
    Max compat profile version: 3.0
    Max GLES1 profile version: 1.1
    Max GLES[23] profile version: 3.0
OpenGL core profile version string: 3.3 (Core Profile) Mesa 12.0.6
OpenGL core profile shading language version string: 3.30
OpenGL version string: 3.0 Mesa 12.0.6
OpenGL shading language version string: 1.30
OpenGL ES profile version string: OpenGL ES 3.0 Mesa 12.0.6
OpenGL ES profile shading language version string: OpenGL ES GLSL ES 3.00

**Comment by SimonDanisch** [comment]
Ah, is this on a VM with Mesa?
If so, that seems to be a bug in Mesa, or so:(
I tried to debug it once, but wasn't getting very far...

**Comment by SimonDanisch** [comment]
Seems like not many people use the Mesa software rendering for more complex things. Which is understandable, considering that it will be very slow for anything non trivial ;)

**Comment by ERPPC** [comment]
Does this mean this package won't work in an Ubuntu VM?

I will try the same install procedure on a non-vm machine tonight and see if it works.

**Comment by SimonDanisch** [comment]
Yeah, VM's getter better and better at supporting OpenGL, but it's still not fully there, especially with older GPU's :( I heard rumors, that OpenGL acceleration should work on windows VM's, but so far I haven't had any luck with that.
Ubuntu not in a VM should work!

**Comment by ERPPC** [comment]
Alright. Thanks for your replies Simon!
