### ISSUE TITLE
Writing to video, scripting transformations

### ISSUE THREAD

**Issue by Cody-G** [JuliaGL/GLVisualize.jl#151]
I was referring to #117 and I wonder is there an updated example for this somewhere?  Seems that `GLWindow.pollevents` no longer exists.

What I would like to do for now is to create videos without interactivity, just by scripting a set of transformations, updating the image, and writing the image to a file.  I'm new to OpenGL and to this package so I may be missing an obvious way to do this :)  Thanks! #

**Comment by SimonDanisch** [comment]
yes there is a new fast way of doing this :)
Let me finally create an example for this often asked question!

**Comment by SimonDanisch** [comment]
Hope this  helps: 
https://github.com/JuliaGL/GLVisualize.jl/blob/5c979d5601a7352e26abe283c0f8079334154529/examples/introduction/video_recording.jl

**Comment by Cody-G** [comment]
That works beautifully for me, thanks!!
