### ISSUE TITLE
UndefVarError: post_empty not defined

### ISSUE THREAD

**Issue by olegmikul** [JuliaGL/GLVisualize.jl#154]
Hi, 

The error happened for some examples:
>>><<<
julia> include("/home/uname/.julia/v0.5/GLVisualize/examples/plots/drawing.jl")
ERROR: LoadError: UndefVarError: post_empty not defined
 in _display(::Plots.Plot{Plots.GLVisualizeBackend}, ::Bool) at /home/uname/.julia/v0.5/Plots/src/backends/glvisualize.jl:1185
 in gui(::Plots.Plot{Plots.GLVisualizeBackend}) at /home/uname/.julia/v0.5/Plots/src/output.jl:123 (repeats 2 times)
 in include_from_node1(::String) at ./loading.jl:488
while loading /home/uname/.julia/v0.5/GLVisualize/examples/plots/drawing.jl, in expression starting on line 24
>>><<<

Versions:
Julia:
Version 0.5.2-pre+1 (2017-03-06 03:59 UTC)
Commit a6c55c5* (7 days old release-0.5)
x86_64-redhat-linux

Pkg:
18 required packages:
 - Contour                       0.2.0
 - GLVisualize                   0.2.2
 - GR                            0.19.0
 - IJulia                        1.4.1
 - ImageMagick                   0.2.2
 - InspectDR                     0.1.6
 - JuliaParser                   0.7.4
 - Knet                          0.8.2
 - Mocha                         0.2.0
 - ParallelAccelerator           0.2.2              6da2e374 (dirty)
 - PlotRecipes                   0.2.0
 - PlotlyJS                      0.5.2
 - Plots                         0.10.3
 - PyPlot                        2.3.1
 - RDatasets                     0.2.0
 - Rsvg                          0.0.2              d8374212 (dirty)
 - StatPlots                     0.2.1
 - Winston                       0.12.1
118 additional packages:
 - AbstractTrees                 0.1.0
 - AutoGrad                      0.0.6
 - AxisAlgorithms                0.1.6
 - AxisArrays                    0.0.6
 - BaseTestNext                  0.2.2
 - BinDeps                       0.4.7
 - Blink                         0.5.1
 - Blosc                         0.2.0
 - Cairo                         0.2.35
 - Calculus                      0.2.1
 - CatIndices                    0.0.2
 - Codecs                        0.3.0
 - ColorTypes                    0.3.5
 - ColorVectorSpace              0.4.0
 - Colors                        0.7.3
 - Compat                        0.20.0
 - CompilerTools                 0.2.1
 - ComputationalResources        0.0.2
 - Conda                         0.5.1
 - CoordinateTransformations     0.4.0
 - CustomUnitRanges              0.0.4
 - DataArrays                    0.3.12
 - DataFrames                    0.9.0
 - DataStructures                0.5.2              402a6d45 (dirty)
 - Dates                         0.4.4
 - DiffBase                      0.0.4
 - Distributions                 0.12.1
 - DocOpt                        0.2.1
 - DocStringExtensions           0.3.1
 - DualNumbers                   0.3.0
 - FFTViews                      0.0.2
 - FileIO                        0.3.0
 - FixedPointNumbers             0.3.5
 - FixedSizeArrays               0.2.5
 - ForwardDiff                   0.4.0
 - FreeType                      1.2.0
 - GLAbstraction                 0.3.1
 - GLFW                          1.3.0
 - GLWindow                      0.3.2
 - GZip                          0.2.20
 - GeometryTypes                 0.2.2
 - Graphics                      0.1.4
 - Gtk                           0.12.0
 - HDF5                          0.7.3
 - Hiccup                        0.1.1
 - HttpCommon                    0.2.6
 - HttpParser                    0.2.0
 - HttpServer                    0.1.7
 - ImageAxes                     0.1.1
 - ImageCore                     0.1.5
 - ImageFiltering                0.1.2
 - ImageMetadata                 0.2.1
 - ImageTransformations          0.1.0
 - Images                        0.8.0
 - IndirectArrays                0.1.1
 - IniFile                       0.3.1
 - Interpolations                0.3.8
 - IntervalSets                  0.0.4
 - Iterators                     0.3.0
 - JLD                           0.6.9
 - JSON                          0.8.3
 - Juno                          0.2.7
 - KernelDensity                 0.3.2
 - LaTeXStrings                  0.2.0
 - Lazy                          0.11.5
 - LegacyStrings                 0.2.0
 - LineSearches                  0.1.5
 - Logging                       0.3.1
 - MacroTools                    0.3.6
 - MappedArrays                  0.0.7
 - MbedTLS                       0.4.3
 - Measures                      0.0.3
 - Media                         0.2.5
 - MeshIO                        0.0.6
 - ModernGL                      0.1.1
 - Mustache                      0.1.3
 - Mux                           0.2.3
 - NaNMath                       0.2.2
 - Nettle                        0.3.0
 - NetworkLayout                 0.0.1
 - NumericIO                     0.1.0
 - OffsetArrays                  0.2.14
 - Optim                         0.7.8
 - PDMats                        0.5.6
 - Packing                       0.0.4
 - PlotThemes                    0.1.1
 - PlotUtils                     0.3.0
 - PositiveFactorizations        0.0.4
 - PyCall                        1.11.0
 - QuadGK                        0.1.1
 - Quaternions                   0.1.1
 - RData                         0.0.4
 - RangeArrays                   0.1.2
 - Ratios                        0.0.4
 - Reactive                      0.3.7
 - RecipesBase                   0.1.0
 - Reexport                      0.0.3
 - Rmath                         0.1.6
 - Rotations                     0.3.5
 - SHA                           0.3.2
 - SIUnits                       0.1.0
 - ShowItLikeYouBuildIt          0.0.1
 - Showoff                       0.0.7
 - SignedDistanceFields          0.1.0
 - SimpleTraits                  0.3.0
 - SortingAlgorithms             0.1.0
 - SpecialFunctions              0.1.1
 - StaticArrays                  0.3.0
 - StatsBase                     0.13.1
 - StatsFuns                     0.4.0
 - TexExtensions                 0.0.3
 - TiledIteration                0.0.2
 - Tk                            0.4.0
 - URIParser                     0.1.7              df52383c (dirty)
 - UnicodeFun                    0.0.2
 - WebSockets                    0.2.1
 - WoodburyMatrices              0.2.2
 - ZMQ                           0.4.1

**Comment by SimonDanisch** [comment]
Oh yeah, I need to merge sd/dev in Plots.jl: https://github.com/JuliaPlots/Plots.jl/pull/729
