### ISSUE TITLE
Interactive renderloop - question

### ISSUE THREAD

**Issue by Benoit9** [JuliaGL/GLVisualize.jl#160]
Hello,
Is it currently possible to start the renderloop and get back to the repl prompt? Something like the interactive mode in matplotlib? In that mode the graphical window is reactive, but the contents can be changed from the command line, additional windows can be created, etc.
I looked at the examples and at GLWindow/render.jl but I don't see anything like it.
Do you have any suggestion?
Thank you very much!

**Comment by SimonDanisch** [comment]
Yes!
```Julia
using GLVisualize; w = glscreen(); @async renderloop(w)
```

Best,
Simon

**Comment by Benoit9** [comment]
Ha! Amazing. Thank you so much!
Great package BTW.

**Comment by SimonDanisch** [comment]
By the way, there is also `GLWindow.waiting_renderloop(w)`, which won't heat up the GPU as much, but won't update when you directly manipulate any visualisation in the REPL (you need a Reactive event to trigger the update).

**Comment by Benoit9** [comment]
Thanks! I had seen that function, but wasn't sure what it was for.

**Comment by SimonDanisch** [comment]
I should definitely add more documentation for those! ;)

**Comment by Benoit9** [comment]
I have been working with the examples and looking at the code when needed.

You must be aware that http://www.glvisualize.com/api/ is missing a lot of important functions (visualize, _view)? Or did I miss the latest docs?

**Comment by SimonDanisch** [comment]
Oh yeah, the docs are super out of date... I want to build the docs with the CI, but there were always some problems so far -.-
