### ISSUE TITLE
Screen not centered

### ISSUE THREAD

**Issue by nico202** [JuliaGL/GLVisualize.jl#165]
I'm trying to write a game using GLVisualize, but I find it difficult to center things on the screen. For example, the **moving bars** code http://www.glvisualize.com/examples/sprites/#moving-bars 
Renders like this screenshot:
![2017-04-18-16 13 43_1366x768_scrot](https://cloud.githubusercontent.com/assets/8214542/25135271/2c4a6d12-2452-11e7-97f0-5da3df98da7b.png)

The same holds true for all other examples, like the following (lower left corner)
How do I adjust it?

**Comment by SimonDanisch** [comment]
is the camera with pan and zoom not working?

**Comment by nico202** [comment]
I can control the camera in the examples where ```camera == :perspective```. , but in those examples the objects are already centered. The problem comes bu setting ```camera = :fixed_pixel``` : the object seems not to be rendered (as it's always out of the view) and I can't look for it with pan, as expected

**Comment by SimonDanisch** [comment]
it's _fixed_ pixels ... If you don't want things to be fixed, don't use the fixed pixel camera!
You should use orthographic_pixel in that case :)

**Comment by nico202** [comment]
Ahah yes I know what fixed stand for. And I don't want to be able to move the camera, so fixed pixel is what I want. The problem was that I was not able to place the drawing on the screen. I just realized that the coordinate system is not 0.0-1.0 but depends on the screen pixel size, so I was drawing in 1 pixel only :(
Is there something like a trasformation matrix? for example where Point2f0(0.0,0.0) is the center of the screen regardless of the screen size

**Comment by nico202** [comment]
My bad. There's translationmatrix and scalematrix, I should have payed more attention to the examples. Sorry for the noise. This package is really wonderful, thanks :)

**Comment by SimonDanisch** [comment]
No worries! The documentation is definitely something that needs a lot more work!
Sorry, I completely forgot to get back to your question :(
Glad you figured it out! :)
