### ISSUE TITLE
LLVM ERROR: Inline asm not supported by this streamer because we don't have an asm parser for this target

### ISSUE THREAD

**Issue by flo12345678** [JuliaGL/GLVisualize.jl#166]
labuser@HP-Z420-Workstation:~$ julia
               _
   _       _ _(_)_     |  A fresh approach to technical computing
  (_)     | (_) (_)    |  Documentation: http://docs.julialang.org
   _ _   _| |_  __ _   |  Type "?help" for help.
  | | | | | | |/ _` |  |
  | | |_| | | | (_| |  |  Version 0.5.1 (2017-03-05 13:25 UTC)
 _/ |\__'_|_|_|\__'_|  |  Official http://julialang.org/ release
|__/                   |  x86_64-pc-linux-gnu

julia> using GLVisualize, GLWindow

julia> window = glscreen()
LLVM ERROR: Inline asm not supported by this streamer because we don't have an asm parser for this target

labuser@HP-Z420-Workstation:~$ julia
               _
   _       _ _(_)_     |  A fresh approach to technical computing
  (_)     | (_) (_)    |  Documentation: http://docs.julialang.org
   _ _   _| |_  __ _   |  Type "?help" for help.
  | | | | | | |/ _` |  |
  | | |_| | | | (_| |  |  Version 0.5.1 (2017-03-05 13:25 UTC)
 _/ |\__'_|_|_|\__'_|  |  Official http://julialang.org/ release
|__/                   |  x86_64-pc-linux-gnu

julia> versioninfo()
Julia Version 0.5.1
Commit 6445c82 (2017-03-05 13:25 UTC)
Platform Info:
  OS: Linux (x86_64-pc-linux-gnu)
  CPU: Intel(R) Xeon(R) CPU E5-1620 0 @ 3.60GHz
  WORD_SIZE: 64
  BLAS: libopenblas (USE64BITINT DYNAMIC_ARCH NO_AFFINITY Sandybridge)
  LAPACK: libopenblas64_
  LIBM: libopenlibm
  LLVM: libLLVM-3.7.1 (ORCJIT, sandybridge)

julia> 
labuser@HP-Z420-Workstation:~$ glxinfo | grep "version"
server glx version string: 1.4
client glx version string: 1.4
GLX version: 1.4
    Max core profile version: 4.3
    Max compat profile version: 3.0
    Max GLES1 profile version: 1.1
    Max GLES[23] profile version: 3.1
OpenGL core profile version string: 4.3 (Core Profile) Mesa 12.0.6
OpenGL core profile shading language version string: 4.30
OpenGL version string: 3.0 Mesa 12.0.6
OpenGL shading language version string: 1.30
OpenGL ES profile version string: OpenGL ES 3.1 Mesa 12.0.6
OpenGL ES profile shading language version string: OpenGL ES GLSL ES 3.10
labuser@HP-Z420-Workstation:~$ 

I tried to use GLVisualize and could somebody give me a hint what am I doing wrong? I don't know which target is meant?

**Comment by SimonDanisch** [comment]
Yes! This happens when you use Mesa's software OpenGL implementation. I think it's a bug on their side. Any chance to install a driver from your gpu vendor?

**Comment by flo12345678** [comment]
Thx for the fast reply! I've changed to the newest nvidia drivers and now it works!

**Comment by SimonDanisch** [comment]
Great! :)
