### ISSUE TITLE
Cannot `convert` an object of type String to an object of type Tuple

### ISSUE THREAD

**Issue by rnoxy** [JuliaGL/GLVisualize.jl#168]
Hello, I am new in Julia and probably I am doing something wrong.

I am trying to have some fun with GLVisualize, but unfortunately I cannot run any code, even tests from the package.

The problem is with the function `visualize` 
giving me LoadError + MethodError

> LoadError: MethodError: Cannot `convert` an object of type String to an object of type Tuple
> This may have arisen from a call to the constructor Tuple(...),
> since type constructors fall back to convert methods.

The same is when I try to do `Pkg.test("GLVisualize")`

I attach the example figure giving this error (working with Atom)
![image](https://cloud.githubusercontent.com/assets/12031664/25519872/e49681c2-2bf9-11e7-997b-8122766061f6.png)

I have julia 0.5.1 installed in Windows 10.

**Comment by SimonDanisch** [comment]
Sorry, this is mainly an issue of tagging which I'm trying to figure out!
Try `Pkg.pin("Reactive", v"0.3.7")`

**Comment by rnoxy** [comment]
I tried
> Pkg.pin("Reactive", v"0.3.7")
> INFO: Creating Reactive branch pinned.1b4e2c05.tmp
> INFO: No packages to install, update or remove

Next I tried to `Pkg.build("GLVisualize")`

That **fixed the problem**. Thanks..

BTW: how to undo this `Pkg.pin("Reactive", v"0.3.7")` later?

--
Rafał

**Comment by SimonDanisch** [comment]
`Pkg.free("Reactive")`.
I just figured out, that this is a fixable bug in Reactive. Will write when fixed!

**Comment by rnoxy** [comment]
Thanks you very much 👍 

I was fighting with this bug all the day yesterday.

**Comment by SimonDanisch** [comment]
Oh no! :( You should open issues quickly with this repository! ;) Worst thing that could happen is that I ignore it or you figure out a fix before me!

**Comment by rnoxy** [comment]
The only thing that I figured out was that this code

> sphere = GLNormalMesh(Sphere(Point3f0(0.5), 0.5f0), 4)
> _view( visualize( sphere ) , window)

do not give the mentioned error. I don't know why.

**Comment by SimonDanisch** [comment]
https://github.com/JuliaGizmos/Reactive.jl/pull/136 Will fix this!
The tagging will be a bit complicated, since there is now a tag in there which has this bug -.-

**Comment by SimonDanisch** [comment]
There have been quite a few bugs in Reactive lately... Please make sure to update to newest Reactive version!
