### ISSUE TITLE
calling visualize() after renderloop()

### ISSUE THREAD

**Issue by nico202** [JuliaGL/GLVisualize.jl#170]
Hi, sorry to bother again, but I can't understand a thing.

example code:
```
function function_that_might_call_visualize_and__view(x)
     if condition_is_true
          el = visualize(things)
          println("called")
          _view(el)
     end
     true
end

foreach(function_that_might_call_visualize_and__view, fps(50))
renderloop(window)
```

In this trivial example, as soon as condition_is_true, the rendering freezes, and "called" is never printed. However if I call visualize and _view _before_ renderloop, they do work.

How am I supposed to add new elements? I can't find an example doing this

Thanks, Nicolò

**Comment by SimonDanisch** [comment]
No worries!
`renderloop(window)` is blocking!
Try `@async renderloop(window)`

**Comment by nico202** [comment]
Yeah I know it's blocking, but the function function_that_might_call_visualize_and__view, since is in a foreach = preserve(map()) _get_ called. Is the fact that it's called that blocks completely the rendering (the scene that was moving, freezes as soon as "condition_is_true" is true).
Indeed, using @async does not help

**Comment by SimonDanisch** [comment]
Ah sorry, didn't look closely enough!
Seems like in your setup, you need to do:
```Julia
@async foreach(function_that_might_call_visualize_and__view, fps(50))
```
I think you might need a yield at the end of `function_that_might_call_visualize_and__view`. Might be fine with Reactive without it.

**Comment by SimonDanisch** [comment]
Ah sorry didn't look closely enough... Btw, are you sure that you want to visualize something every 1/50 seconds ??? That's not how GLVisualize is intended to be used.

**Comment by SimonDanisch** [comment]
I can reproduce your problem and on first sight it looks like a bug...

**Comment by nico202** [comment]
@async + yield() did the tricks however, thanks :)

About fps(), 50Hz is approximately the refresh rate of the monitor, so I thought for a "video game" is the right value. Which frame rate would you use? it works well at this value

**Comment by SimonDanisch** [comment]
No, that's not what I meant, but `_view(visualize)` is not an operation you should do every frame.
It creates a new object on the GPU and puts it into a scene, which you then can manipulate. It's quite expensive and will fill up your GPU's memory.

So you should rather do something like this:
```Julia
x = _view(visualize(...));

function update_loop()
    GLAbstraction.set_arg!(x, :color, newcolor)
end
# or 
color = Signal(color)
x = _view(visualize(..., color = color))
function update_loop()
push!(color, newcolor)
end
```

**Comment by nico202** [comment]
But condition_is_true is a keypress, so it's true rarely.
The fact is that I need to add objects, not change properties of an existing one...

However, there is something strange.
The @async + yield works only if I have a println() statement in the function called..

**Comment by SimonDanisch** [comment]
Ideally, you can create all objects you want to view upfront and then just manipulate those... But of course you can also dynamically insert/delete objects at runtime, as you can see now that your example is working.
Delete is not documented as far as I know (and not implemented very well as it seems) : 
```Julia
x = visualize(...)
delete!(window, x.children[])
```
The x.children is because I didn't implement it for my nested visualize objects.
So what I should add is this function:
```Julia
function Base.delete!(window::Screen, obj::Composable)
for child in obj.children
delete!(window, child)
end
end
```

**Comment by nico202** [comment]
My example is not exactly working, just sometimes. I still do not have the behavior I need.

**Comment by SimonDanisch** [comment]
well, did you try restructuring your code as I explained?

**Comment by nico202** [comment]
I'm creating it before with a scale of 0.0 and then pushing to the scale matrix the value 1.0, but I am still not able to dynamically create them

**Comment by SimonDanisch** [comment]
After some more investigation, I think this must be a Reactive bug! Will look into it today

**Comment by timholy** [comment]
Be sure you test the new Reactive (aka `master`, not yet tagged), it's a very fundamental rewrite and might already fix the bug.

**Comment by SimonDanisch** [comment]
I think it did indeed...needs more testing though

**Comment by SimonDanisch** [comment]
I think I found a possible problem on Reactive master...
Since it was spurious, I don't know for sure though -.-
https://github.com/JuliaGizmos/Reactive.jl/pull/137

**Comment by nico202** [comment]
Cool, thanks for working on this

**Comment by SimonDanisch** [comment]
Please try on Reactive master again! A lot of bugs have been fixed ;)
