### ISSUE TITLE
Use as a Plots.jl backend stalls

### ISSUE THREAD

**Issue by ChrisRackauckas** [JuliaGL/GLVisualize.jl#175]
```julia
julia> using Plots; glvisualize()
WARNING: ImageMetadata.AbstractImage is deprecated, use ImageMetadata.ImageMeta instead.
  likely near no file:69
WARNING: ImageMetadata.AbstractImage is deprecated, use ImageMetadata.ImageMeta instead.
  likely near no file:71
Plots.GLVisualizeBackend()

julia> plot(rand(10,10))
```

And nothing ever comes out.

**Comment by SimonDanisch** [comment]
Can you try updating Reactive to the newest version?

**Comment by ChrisRackauckas** [comment]
Still happens after checking out Reactive.

May want to mention: Windows 10, Julia v0.5.2

**Comment by SimonDanisch** [comment]
Okay.. I'm doing a few non standard things with Reactive in the Plots backend - so maybe the stopped working on newer version... I will have a look at it.

**Comment by SimonDanisch** [comment]
Interesting, for me something comes out, but I can't zoom! Which is the error I've seen elsewhere and is quite likely what I said in my comment before!
Are you on GLVisualize & GLAbstraction master ?

**Comment by ChrisRackauckas** [comment]
>Are you on GLVisualize & GLAbstraction master ?

No I am not. I'll do that soon.

**Comment by mkborregaard** [comment]
I can confirm I have this issue on Mac with 0.5.2, master of Plots, GLVisualize and GLAbstraction. Plots + GLVisualize have such potential :cry:

**Comment by SimonDanisch** [comment]
Okay, I can reproduce this on a fresh install! Let me see if I can also fix it ;)

**Comment by SimonDanisch** [comment]
I think I found it, but it's a bit annoying to fully fix, since the bug is quite deep in Reactive's new implementation -.- ... For now, I have a fix which cleans up signals less (might slow down more and more, when you open new plots a lot), and it renders a frame every 1/60s or so, which drains the GPU much more than the previous version!

**Comment by mkborregaard** [comment]
Still nice :-)
