### ISSUE TITLE
unsatisfiable package requirements

### ISSUE THREAD

**Issue by ptoche** [JuliaGL/GLVisualize.jl#176]
I had to install ImageCore before I could install GLVisualize. I see no warning of this in the ``readme`` file.

    Pkg.add("GLVisualize")
    unsatisfiable package requirements detected: no feasible version could be found for package: ImageCore

The following worked: 

    Pkg.add("ImageCore")
    Pkg.add("GLVisualize")

Testing has failed so far, but it's taking a long time to compile, perhaps I need to be more patient (it's been over 30 minutes though). I'm out of time, so I'll copy the content of the console for your information and try again some other time.

Edit: **Oh wait!** I have a rotating cat. It was in a pop-up window I hadn't seen. Looks like things are working. **Sweet!**

        Pkg.test("GLVisualize")

        INFO: Computing test dependencies for GLVisualize...
        INFO: Cloning cache of Highlights from https://github.com/JuliaDocs/Highlights.jl.git
        INFO: Cloning cache of ImageMagick from https://github.com/JuliaIO/ImageMagick.jl.git
        INFO: Cloning cache of QuartzImageIO from https://github.com/JuliaIO/QuartzImageIO.jl.git
        INFO: Installing Highlights v0.2.1
        INFO: Installing ImageMagick v0.2.4
        INFO: Installing QuartzImageIO v0.2.1
        INFO: Building Homebrew
        Already up-to-date.
        INFO: Building ImageMagick
        ==> Downloading https://homebrew.bintray.com/bottles/xz-5.2.3.yosemite.bottle.tar.gz
        ==> Pouring xz-5.2.3.yosemite.bottle.tar.gz
        🍺  /Users/.../.julia/v0.5/Homebrew/deps/usr/Cellar/xz/5.2.3: 92 files, 1.4MB
        Warning: Already linked: /Users/.../.julia/v0.5/Homebrew/deps/usr/Cellar/xz/5.2.3
        ==> Installing jpeg from staticfloat/juliatranslated
        ==> Downloading https://homebrew.bintray.com/bottles/jpeg-8d.yosemite.bottle.2.tar.gz
        ==> Pouring jpeg-8d.yosemite.bottle.2.tar.gz
        🍺  /Users/.../.julia/v0.5/Homebrew/deps/usr/Cellar/jpeg/8d: 19 files, 731.3KB
        Warning: Already linked: /Users/.../.julia/v0.5/Homebrew/deps/usr/Cellar/jpeg/8d
        ==> Installing libtiff from staticfloat/juliatranslated
        ==> Downloading https://homebrew.bintray.com/bottles/libtiff-4.0.7_3.yosemite.bottle.tar.gz
        ==> Pouring libtiff-4.0.7_3.yosemite.bottle.tar.gz
        🍺  /Users/.../.julia/v0.5/Homebrew/deps/usr/Cellar/libtiff/4.0.7_3: 248 files, 3.4MB
        Warning: Already linked: /Users/.../.julia/v0.5/Homebrew/deps/usr/Cellar/libtiff/4.0.7_3
        ==> Installing libtool from staticfloat/juliatranslated
        ==> Downloading https://homebrew.bintray.com/bottles/libtool-2.4.6_1.yosemite.bottle.tar.gz
        ==> Pouring libtool-2.4.6_1.yosemite.bottle.tar.gz
        ==> Caveats
        In order to prevent conflicts with Apple's own libtool we have prepended a "g"
        so, you have instead: glibtool and glibtoolize.
        ==> Summary
        🍺  /Users/.../.julia/v0.5/Homebrew/deps/usr/Cellar/libtool/2.4.6_1: 70 files, 3.7MB
        Warning: Already linked: /Users/.../.julia/v0.5/Homebrew/deps/usr/Cellar/libtool/2.4.6_1
        ==> Installing imagemagick@6 from staticfloat/juliatranslated
        ==> Downloading https://homebrew.bintray.com/bottles/imagemagick@6-6.9.8-5.yosemite.bottle.tar.gz
        ==> Pouring imagemagick@6-6.9.8-5.yosemite.bottle.tar.gz
        ==> Caveats
        This formula is keg-only, which means it was not symlinked into /Users/.../.julia/v0.5/Homebrew/deps/usr.

        This is an alternate version of another formula.

        If you need to have this software first in your PATH run:
          echo 'export PATH="/Users/.../.julia/v0.5/Homebrew/deps/usr/opt/imagemagick@6/bin:$PATH"' >> ~/.bash_profile

        For compilers to find this software you may need to set:
            LDFLAGS:  -L/Users/.../.julia/v0.5/Homebrew/deps/usr/opt/imagemagick@6/lib
            CPPFLAGS: -I/Users/.../.julia/v0.5/Homebrew/deps/usr/opt/imagemagick@6/include
        For pkg-config to find this software you may need to set:
            PKG_CONFIG_PATH: /Users/.../.julia/v0.5/Homebrew/deps/usr/opt/imagemagick@6/lib/pkgconfig

        ==> Summary
        🍺  /Users/.../.julia/v0.5/Homebrew/deps/usr/Cellar/imagemagick@6/6.9.8-5: 1,469 files, 22.6MB
        INFO: Testing GLVisualize
        WARNING: ColorTypes.U8 is deprecated, use FixedPointNumbers.Normed{UInt8, 8} instead.
          likely near /Users/.../.julia/v0.5/GeometryTypes/src/typealias.jl:90
        WARNING: ImageMetadata.Image is deprecated, use ImageMetadata.ImageMeta instead.
          likely near /Users/.../.julia/v0.5/GLVisualize/src/utils.jl:8
        WARNING: ImageMetadata.Image is deprecated, use ImageMetadata.ImageMeta instead.
          likely near /Users/.../.julia/v0.5/GLVisualize/src/visualize/image_like.jl:1
        WARNING: ImageMetadata.Image is deprecated, use ImageMetadata.ImageMeta instead.
          likely near /Users/.../.julia/v0.5/GLVisualize/src/visualize/image_like.jl:3
        WARNING: ImageMetadata.Image is deprecated, use ImageMetadata.ImageMeta instead.
          likely near /Users/.../.julia/v0.5/GLVisualize/src/visualize/image_like.jl:480
        WARNING: ImageMetadata.Image is deprecated, use ImageMetadata.ImageMeta instead.
          likely near /Users/.../.julia/v0.5/GLVisualize/src/visualize/image_like.jl:481
        WARNING: ImageMetadata.Image is deprecated, use ImageMetadata.ImageMeta instead.
          likely near /Users/.../.julia/v0.5/GLVisualize/src/visualize/image_like.jl:480
        WARNING: ImageMetadata.Image is deprecated, use ImageMetadata.ImageMeta instead.
          likely near /Users/.../.julia/v0.5/GLVisualize/src/visualize/image_like.jl:481
        WARNING: ImageMetadata.Image is deprecated, use ImageMetadata.ImageMeta instead.
          likely near /Users/.../.julia/v0.5/GLVisualize/src/visualize/particles.jl:480
        WARNING: ImageMetadata.Image is deprecated, use ImageMetadata.ImageMeta instead.
          likely near /Users/.../.julia/v0.5/GLVisualize/src/visualize/particles.jl:481
        INFO: Caching fonts, this may take a while. Needed only on first run!

**Comment by timholy** [comment]
What's your julia version? 0.5.2 had some fixes to package resolution.

**Comment by ptoche** [comment]
@timholy, thanks. I'm on 0.5.1. I'll update asap. 

As an aside: every day Julia asks me to run ``Pkg.update()`` and I spend more time than I would like doing it. But total silence about the existence of a new version of Julia. Thanks for the heads up.

**Comment by SimonDanisch** [comment]
>every day Julia asks me to run Pkg.update()

I've never seen that. Maybe some package you are using is asking you this?
I can't see a reason to update daily!

**Comment by ptoche** [comment]
@SimonDanisch, Ah I'm glad to hear this. 

As an experiment, after about 10 hours of not using Julia, I ran the following code. It took about 5 minutes to get a plot out. This time around it did not ask me to run ``Pkg.udpate()``, but more often than not I get asked to do that after a ``stale cache file`` message. I forgot to do a proper timing of this.

I then closed Julia and restarted a session and ran the code again. This time I timed it. It took 39.7 seconds, which is what I would imagine it would take to compile the code. But everyday I experience a situation where the code has to compile for a good 5 minutes and/or ``Pkg.update()`` has to be run. As I speak, I have one package waiting to be updated, but I won't until I'm forced to. ;-)

        using Plots
        plot(sin, -2pi, pi, label="sine function") 
        INFO: Recompiling stale cache file /Users/.../.julia/lib/v0.5/MbedTLS.ji for module MbedTLS.
        INFO: Recompiling stale cache file /Users/.../.julia/lib/v0.5/Atom.ji for module Atom.
        WARNING: using Lazy.remove in module AtomShell conflicts with an existing identifier.
        INFO: Recompiling stale cache file /Users/.../.julia/lib/v0.5/PlotUtils.ji for module PlotUtils.
        INFO: Recompiling stale cache file /Users/.../.julia/lib/v0.5/PlotThemes.ji for module PlotThemes.
        INFO: Recompiling stale cache file /Users/.../.julia/lib/v0.5/Showoff.ji for module Showoff.
        WARNING: Method definition show(IO, Base.Multimedia.MIME{:text/plain}, Plots.Plot{#B<:Any}) in module Plots at /Users/.../.julia/v0.5/Plots/src/output.jl:196 overwritten in module Main at /Users/.../.julia/v0.5/Plots/src/output.jl:289.
        INFO: Recompiling stale cache file /Users/.../.julia/lib/v0.5/PyPlot.ji for module PyPlot.

**Comment by ptoche** [comment]
As of today, I have updated Julia to version 0.5.2. I had problems with ``linter-ui-default`` being unable to update, so I removed it. I was able to run the test again. This time it took about 15 minutes to get a rotating cat and the following info was spilled into the console:

        NFO: Computing test dependencies for GLVisualize...
        INFO: Installing Highlights v0.2.1
        INFO: Installing ImageMagick v0.2.4
        INFO: Installing QuartzImageIO v0.2.1
        INFO: Building Homebrew
        Updated 1 tap (homebrew/core).
        ==> Updated Formulae
        apache-brooklyn-cli
        aws-sdk-cpp
        awscli
        carthage
        citus
        cnats
        convox
        deis
        dhall-json
        digdag
        dropbear
        etcd
        exa
        fio
        fonttools
        freetds
        geoserver
        git-annex
        git-lfs
        gofabric8
        grpc
        gtk-vnc
        immortal
        inspircd
        jasper
        jbig2dec
        jlog
        jo
        libatomic_ops
        minidlna
        mongoose
        mono
        mpd
        mps-youtube
        mysql-connector-c++
        nano
        nginx
        nim
        npth
        open-scene-graph
        pegtl
        prometheus
        radare2
        redis
        rocksdb
        shc
        sphinx-doc
        swi-prolog
        tarantool
        testssl
        tor
        uncrustify
        unrar
        watchexec
        youtube-dl
        INFO: Building ImageMagick
        INFO: Testing GLVisualize
        WARNING: ColorTypes.U8 is deprecated, use FixedPointNumbers.Normed{UInt8, 8} instead.
          likely near /Users/.../.julia/v0.5/GeometryTypes/src/typealias.jl:90
        WARNING: ImageMetadata.Image is deprecated, use ImageMetadata.ImageMeta instead.
          likely near /Users/.../.julia/v0.5/GLVisualize/src/utils.jl:8
        WARNING: ImageMetadata.Image is deprecated, use ImageMetadata.ImageMeta instead.
          likely near /Users/.../.julia/v0.5/GLVisualize/src/visualize/image_like.jl:1
        WARNING: ImageMetadata.Image is deprecated, use ImageMetadata.ImageMeta instead.
          likely near /Users/.../.julia/v0.5/GLVisualize/src/visualize/image_like.jl:3
        WARNING: ImageMetadata.Image is deprecated, use ImageMetadata.ImageMeta instead.
          likely near /Users/.../.julia/v0.5/GLVisualize/src/visualize/image_like.jl:480
        WARNING: ImageMetadata.Image is deprecated, use ImageMetadata.ImageMeta instead.
          likely near /Users/.../.julia/v0.5/GLVisualize/src/visualize/image_like.jl:481
        WARNING: ImageMetadata.Image is deprecated, use ImageMetadata.ImageMeta instead.
          likely near /Users/.../.julia/v0.5/GLVisualize/src/visualize/image_like.jl:480
        WARNING: ImageMetadata.Image is deprecated, use ImageMetadata.ImageMeta instead.
          likely near /Users/.../.julia/v0.5/GLVisualize/src/visualize/image_like.jl:481
        WARNING: ImageMetadata.Image is deprecated, use ImageMetadata.ImageMeta instead.
          likely near /Users/.../.julia/v0.5/GLVisualize/src/visualize/particles.jl:480
        WARNING: ImageMetadata.Image is deprecated, use ImageMetadata.ImageMeta instead.
          likely near /Users/.../.julia/v0.5/GLVisualize/src/visualize/particles.jl:481

**Comment by mkborregaard** [comment]
The "METADATA may be out of date" warning can be safely ignored. No reason to Pkg.update() all the time.

**Comment by ptoche** [comment]
Got it, thanks!
