### ISSUE TITLE
GLVisualize slows down MacOS

### ISSUE THREAD

**Issue by StreetLevel** [JuliaGL/GLVisualize.jl#181]
Hi Simon,
I'm using GLVisualize on the new Macbook Pro Touch with Intel Iris Graphic 550 and Mac OS 10.12.4 installed. When im running GLVisualize my whole system slows down and especially the Mac OS Graphic Frontend is getting extremely slow and laggy. When I close the GLVisualize window nothing change until i quit Julia completely.
Best Max

**Comment by SimonDanisch** [comment]
Hi Robert,
what code where you trying to execute?
Is this the currently tagged version?

**Comment by StreetLevel** [comment]
After a Pkg.update() i cannot recover the problem. I close this one for now and reopen it, if i can reproduce it.

**Comment by SimonDanisch** [comment]
Yeah there were quite a few problems with Reactive and such....
