### ISSUE TITLE
Error using savefig() when using GLVisualize as backend for Plots.jl

### ISSUE THREAD

**Issue by jdnz** [JuliaGL/GLVisualize.jl#184]
Trying to save a plot to a file using:
```
using Plots, GLVisualize
glvisualize()
plot(randn(10, 10, 10))
savefig("rand_plot")
```
Gives me the following error:
```
ERROR: "colorspace" property is ignored, now color is encoded only by the element type.
See `colorview` to represent a numeric array as a color array.
 in check_deprecated_properties(::Array{ColorTypes.RGB{FixedPointNumbers.Normed{UInt8,8}},2}, ::Dict{String,Any}) at /home/jdouglas/.julia/v0.5/ImageMetadata/src/deprecated.jl:76
 in Type at /home/jdouglas/.julia/v0.5/ImageMetadata/src/ImageMetadata.jl:47 [inlined]
 in Type at /home/jdouglas/.julia/v0.5/ImageMetadata/src/ImageMetadata.jl:51 [inlined]
 in #ImageMeta#1 at /home/jdouglas/.julia/v0.5/ImageMetadata/src/ImageMetadata.jl:52 [inlined]
 in (::Core.#kw#Type)(::Array{Any,1}, ::Type{ImageMetadata.ImageMeta}, ::Array{ColorTypes.RGB{FixedPointNumbers.Normed{UInt8,8}},2}) at ./<missing>:0
 in _show(::IOStream, ::MIME{Symbol("image/png")}, ::Plots.Plot{Plots.GLVisualizeBackend}) at /home/jdouglas/.julia/v0.5/Plots/src/backends/glvisualize.jl:1151
 in show(::IOStream, ::MIME{Symbol("image/png")}, ::Plots.Plot{Plots.GLVisualizeBackend}) at /home/jdouglas/.julia/v0.5/Plots/src/output.jl:197
 in png(::Plots.Plot{Plots.GLVisualizeBackend}, ::String) at /home/jdouglas/.julia/v0.5/Plots/src/output.jl:8
 in savefig(::Plots.Plot{Plots.GLVisualizeBackend}, ::String) at /home/jdouglas/.julia/v0.5/Plots/src/output.jl:116
 in savefig(::String) at /home/jdouglas/.julia/v0.5/Plots/src/output.jl:118
```
The output file is created but is empty. I'm using the release versions julia 0.5.2 on ubuntu, plots 0.11.3, glvisualize 0.3.0. Perhaps it works in development versions? Or is there some other way to save figures?

**Comment by SimonDanisch** [comment]
This looks like like the savefig function isn't updated to work with the current version of the images packages

**Comment by SimonDanisch** [comment]
https://github.com/JuliaPlots/Plots.jl/blob/master/src/backends/glvisualize.jl#L1151
This line must be wrong nowadays!

**Comment by jdnz** [comment]
Thanks! At least in my case, removing ` colorspace = "sRGB", spatialorder = ["y", "x"]` from that line gets rid of the error and the plot is now saved correctly to file. I'm not familiar with the Images package, so I don't know if the above parameters should be replaced with something for more general functionality.

**Comment by SimonDanisch** [comment]
Yeah, I forgot the correct way as well... I guess It'd be via constructing an axis array ;)

**Comment by jaakkor2** [comment]
FWIW, the example works on Windows, Julia 0.6.0, Plots 0.13.1, GLVisualize 0.6.1,..
![rand_plot](https://user-images.githubusercontent.com/7318249/31867410-82d0b986-b78f-11e7-88a6-b9b2b6dc1a3e.png)
