### ISSUE TITLE
Coloring vertices of an unoriented mesh

### ISSUE THREAD

**Issue by jaakkor2** [JuliaGL/GLVisualize.jl#205]
The example tries to use a uniformly colored vertices, but the result is not a uniformly colored surface if the faces are not uniformly oriented (change the line starting with `if true` to `if false` to see the difference).

Any options on the GLVisualize side?

Orienting the faces is one option, if I manage to write a fast enough function.  Apparently such function does not yet exist in Julia based on responses to https://stackoverflow.com/questions/46759661/function-to-re-orient-faces-in-julia and https://discourse.julialang.org/t/function-to-re-orient-mesh-faces/6499 

```julia
using GLVisualize, GeometryTypes, GLWindow, GLAbstraction, Colors

n = 30 # n*n vertices
v = vcat( [ [x y 0] for y=linspace(-1.0,1.0,n) for x=linspace(-1.0,1.0,n)]...) # vertices
twofaces = [
    1 1+n 2
    2 1+n 2+n
]
f = [] # faces
for i=1:n-2
    for j=1:n-2
        f = [ f; twofaces+i+n*j]
    end
end
if true # DEBUG set true to flip the orientation of some faces, set false to have oriented faces
    for i=1:2:size(f,1)
        f[i,:] = flipdim( f[i,:],1 )
    end
end

v2 = [ Point{3,Float32}( v[i,1],v[i,2],v[i,3] ) for i=1:size(v,1) ]
f2 = [ Face{3,UInt32}( f[i,1],f[i,2],f[i,3] ) for i=1:size(f,1) ]

mesh =  GLNormalAttributeMesh(
            vertices=v2, faces=f2,
            attributes=RGBA{Float32}[RGBA{Float32}( 0.0, 1.0, 0.0, 1.0 )], attribute_id=zeros( length( v2 ) )
        )

window = glscreen()
_view( visualize( mesh ), window )
renderloop( window )
```
![image](https://user-images.githubusercontent.com/7318249/31867288-fd1d418a-b78c-11e7-9f4d-5c74302785b1.png)

**Comment by SimonDanisch** [comment]
You could adapt the shading to ignore the orientation of the normals ;) or just disable shading if that's an option. On newest GLVisualize, the kw_arg to `visusalize(mesh, shading = false)` should work!

**Comment by jaakkor2** [comment]
I need shading to see a 3d structure. Option to ignore the orientation of the normals would be nice addition :)  I think I have to try to make the orienting of the surface to work at decent speed.

**Comment by SimonDanisch** [comment]
I think the real problem is, that you have quite a few NaNs in your normals, because a lot of normals are zero which when getting normalized becomes NaN. 
Not sure where exactly the problem lies, but I'd recommend looking at https://github.com/JuliaGeometry/GeometryTypes.jl/blob/master/src/algorithms.jl#L10
which is the function that creates the normals for the GLNormalMesh!

**Comment by jaakkor2** [comment]
Indeed, if two adjacent faces on the same plane have opposite face normals, then vertex normals can become zero. Closing the issue.
