### ISSUE TITLE
Pkg.test demo code in code tab does not scroll

### ISSUE THREAD

**Issue by CrashBurnRepeat** [JuliaGL/GLVisualize.jl#209]
When going through the demos, I have tried to view the individual demo code through the link in the GUI. However, I am unable to scroll, either by click-hold-dragging or by (since I have a trackpad) two-finger scrolling. I have been able to use the trackpad gestures to manipulate objects in the GLVisualize demo, so I'm not sure what about the text environment is different.

System information:
Graphics/Displays:

    Intel HD Graphics 530:

      Chipset Model: Intel HD Graphics 530
      Type: GPU
      Bus: Built-In
      VRAM (Dynamic, Max): 1536 MB
      Vendor: Intel (0x8086)
      Device ID: 0x191b
      Revision ID: 0x0006
      Automatic Graphics Switching: Supported
      gMux Version: 4.0.29 [3.2.8]
      Metal: Supported

    Radeon Pro 460:

      Chipset Model: AMD Radeon Pro 460
      Type: GPU
      Bus: PCIe
      PCIe Lane Width: x8
      VRAM (Total): 4096 MB
      Vendor: ATI (0x1002)
      Device ID: 0x67ef
      Revision ID: 0x00c0
      ROM Revision: 113-C980AF-908
      Automatic Graphics Switching: Supported
      gMux Version: 4.0.29 [3.2.8]
      EFI Driver Version: 01.00.908
      Metal: Supported
      Displays:
        Color LCD:
          Display Type: Built-In Retina LCD
          Resolution: 2880 x 1800 Retina
          Pixel Depth: 32-Bit Color (ARGB8888)
          Main Display: Yes
          Mirror: Off
          Online: Yes
          Rotation: Supported
          Automatically Adjust Brightness: No
          Connection Type: DisplayPort

Hardware:

    Hardware Overview:

      Model Name: MacBook Pro
      Model Identifier: MacBookPro13,3
      Processor Name: Intel Core i7
      Processor Speed: 2.9 GHz
      Number of Processors: 1
      Total Number of Cores: 4
      L2 Cache (per Core): 256 KB
      L3 Cache: 8 MB
      Memory: 16 GB
      Boot ROM Version: MBP133.0226.B25
      SMC Version (system): 2.38f7

Memory:

    Memory Slots:

      ECC: Disabled
      Upgradeable Memory: No

        BANK 0/DIMM0:

          Size: 8 GB
          Type: LPDDR3
          Speed: 2133 MHz
          Status: OK
          Manufacturer: 0x802C
          Part Number: 0x4D5435324C31473332443450472D30393320

        BANK 1/DIMM0:

          Size: 8 GB
          Type: LPDDR3
          Speed: 2133 MHz
          Status: OK
          Manufacturer: 0x802C
          Part Number: 0x4D5435324C31473332443450472D30393320

NVMExpress:

    Apple SSD Controller:

        APPLE SSD SM1024L:

          Capacity: 1 TB (1,000,555,581,440 bytes)
          TRIM Support: Yes
          Model: APPLE SSD SM1024L
          Revision: CXS6AA0Q
          Link Width: x4
          Link Speed: 8.0 GT/s
          Detachable Drive: No
          BSD Name: disk0
          Partition Map Type: GPT (GUID Partition Table)
          Removable Media: No

Software:

    System Software Overview:

      System Version: macOS 10.12.6 (16G29)
      Kernel Version: Darwin 16.7.0
      Time since boot: 8 days 1:51

**Comment by CrashBurnRepeat** [comment]
Also, if it helps, this is my trackpad's system information:

SPI:

    Apple Internal Keyboard / Trackpad:

      Product ID: 0x0278
      Vendor ID: 0x05ac (Apple Inc.)
      Version: 8.79
      Manufacturer: Apple Inc.
      Location ID: 0x01000000

**Comment by SimonDanisch** [comment]
duplication of #217
