### ISSUE TITLE
"documentation.jl" appears twice in the repo

### ISSUE THREAD

**Issue by CrashBurnRepeat** [JuliaGL/GLVisualize.jl#218]
In investigating another issue, I noticed that `documentation.jl` appears in both `src` and `examples/introduction`, and that each version of the file appears to be handling different tasks. In fact, `examples/introduction/documentation.jl` has dependencies on `src/documentation.jl`. Will this cause issues/should one of these be renamed?

**Comment by SimonDanisch** [comment]
No, this is fine ;) One is the implementation (src) the other is an example of the functionality!
