### ISSUE TITLE
easy way to change mouse rotation speed?

### ISSUE THREAD

**Issue by jaakkor2** [JuliaGL/GLVisualize.jl#226]
For me on Windows 7, the mouse rotation speed on perspective camera is way too fast.  Is there an easy way to control it? 

The hard way is to change
https://github.com/JuliaGL/GLAbstraction.jl/blob/master/src/GLCamera.jl#L295
```
inputs, Signal(0.1f0), Signal(1f0), keep
```
to
```
inputs, Signal(0.01f0), Signal(1f0), keep
```
I feel that such a utility function could fall into scope of GLVisualize, that's why I am putting this issue here.

**Comment by SimonDanisch** [comment]
Sorry, forgot about this... Well, bad and good news! I plan to have all attributes of the camera completely customizable... in Makie! :P

**Comment by Hydrolik** [comment]
Not really an easy way to do it, but you can reach and change those signals by digging into the relevant GLWindow.Screen:

```julia
using GLVisualize, Reactive

primitive = loadasset("cat.obj")

window = glscreen()
vis = visualize(primitive)
_view(vis, window)
@async renderloop(window)

# This one is the "Signal(0.1f0)" going into default_camera_control
push!(window.cameras[:perspective].theta.parents[2], 0.01f0)

# And this is the "Signal(1f0)"
push!(window.cameras[:perspective].trans.parents[3], 10f0)
```

**Comment by jaakkor2** [comment]
Great! Thanks. Closing.
