### ISSUE TITLE
GUIs/widgets no longer rendering/functioning properly

### ISSUE THREAD

**Issue by CrashBurnRepeat** [JuliaGL/GLVisualize.jl#237]
I'm guessing another package was recently updated, but a large number of the GUI elements have stopped working for me. For instance, in `fractal_lines.jl`, the sliders, color map, and segment controls no longer have dots showing the break points, but are unresponsive. the thickness GUI still works, but for some reason the lighter background to help make the number visible doesn't seem to be present, or at least not rendering correctly. The image below is what I'm seeing: 

<img width="842" alt="screen shot 2017-12-09 at 8 46 48 pm" src="https://user-images.githubusercontent.com/26471722/33802179-d1a93216-dd25-11e7-9c64-8acccf9cf0c0.png">

This all worked at most a few days ago. Any idea what's changed since then that could cause this?

**Comment by SimonDanisch** [comment]
Sorry about that. What versions are you on?

**Comment by SimonDanisch** [comment]
Oh, I know whats up. let me fix it!

**Comment by SimonDanisch** [comment]
Fixed on GLAbstraction master and waiting for being tagged: https://github.com/JuliaLang/METADATA.jl/pull/12432

**Comment by CrashBurnRepeat** [comment]
Awesome, I checked it out myself and everything seems to be working properly. Thanks!
