### ISSUE TITLE
Scoping error with `filter` function in camera.jl when running GLPlot

### ISSUE THREAD

**Issue by mohamed82008** [JuliaGL/GLVisualize.jl#245]
I got an error when running `GLPlot.init()` from the GLPlot package. The error was in the `filter` function call in line 74 of camera.jl in GLVisualize. The error implied that the `filter` method defined in Reactive was not visible for some reason, could it be using an older Reactive? I resolved the error by replacing `filter` with `Reactive.filter` but I didn't investigate the cause further. I am using checked out GLPlot because the default one was giving a build error of variable not defined somewhere. 

Edit: I suspect this is actually calling the right function, it was the only `filter` method with 3 arguments so I assumed it was the intended one, but I am not so sure of the input types.

Side question: I am trying to play around with interactive 3D visualizations so is GLPlot still the best place to go to, or do you have other recommendations?

**Comment by SimonDanisch** [comment]
Oh no, GLPlot is ancient by now! Sorry about that, I should be clearer about that.
Have a look at Makie, which could be called the new GLPlot: https://github.com/SimonDanisch/MakiE.jl

**Comment by mohamed82008** [comment]
Hmm, does it work with signals, sliders and buttons? MakiE seems very fresh and doesn't have as many examples so it might be hard to play with it unless I read the src which will need more time than I have 😄.

**Comment by SimonDanisch** [comment]
hm that's true... There are some samples in here though:
https://github.com/SimonDanisch/Makie.jl/blob/master/test/all_samples.jl
https://github.com/SimonDanisch/Makie.jl/blob/master/test/moire.jl
https://github.com/SimonDanisch/Makie.jl/tree/master/docs/src/examples

Buttons and other widgets are not as nicely integrated yet, that's true :( but you can just use GLVisualize for that... I see if i have an example for that

**Comment by mohamed82008** [comment]
Thanks for the examples, especially that all_samples file, I will study them thoroughly! Is there any platform like Gitter or Slack for asking specific questions on what certain functions do? Or is Discourse fine?

**Comment by SimonDanisch** [comment]
there is a slack: https://slackinvite.malmaud.com/

**Comment by mohamed82008** [comment]
Plots channel?

**Comment by SimonDanisch** [comment]
for example!
