### ISSUE TITLE
ERROR: GLVisualize test

### ISSUE THREAD

**Issue by kendrick1501** [JuliaGL/GLVisualize.jl#257]
Hi guys,

Currently trying to test GLVisualize.jl but a segmentation error prevents me to do so. I am not sure whether the error is due to my computer configuration or the package itself. I need some help on this, please. Below you can see my Julia version and the glxinfo output.

error> signal (11): Segmentation fault
while loading /mnt/DATA/Julia-PkgDir/v0.6/GLAbstraction/src/GLAbstraction.jl, in expression starting on line 14 unknown function (ip: 0x7fa8a3beaa8f)

julia> versioninfo()
Julia Version 0.6.3
Commit d55cadc (2018-05-28 20:20 UTC)
Platform Info:
  OS: Linux (x86_64-linux-gnu)
  CPU: Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz
  WORD_SIZE: 64
  BLAS: libopenblas (USE64BITINT DYNAMIC_ARCH NO_AFFINITY Haswell)
  LAPACK: libopenblas64_
  LIBM: libopenlibm
  LLVM: libLLVM-3.9.1 (ORCJIT, broadwell)

shell> glxinfo | grep version
server glx version string: 1.4
client glx version string: 1.4
GLX version: 1.4
OpenGL core profile version string: 4.5.0 NVIDIA 396.26
OpenGL core profile shading language version string: 4.50 NVIDIA
OpenGL version string: 4.6.0 NVIDIA 396.26
OpenGL shading language version string: 4.60 NVIDIA
OpenGL ES profile version string: OpenGL ES 3.2 NVIDIA 396.26
OpenGL ES profile shading language version string: OpenGL ES GLSL ES 3.20
    GL_EXT_shader_implicit_conversions, GL_EXT_shader_integer_mix,

**Comment by SimonDanisch** [comment]
Very likely: 
https://github.com/JuliaGL/GLFW.jl/issues/148
Solution:
1) Something wrong with precompilation, you need to restart atom/julia and delete the content of .julia/lib/v0.6/

**Comment by kendrick1501** [comment]
Thanks, @SimonDanisch. The problem is solved now.

Regards.
