### ISSUE TITLE
slerp undefined in camera.jl

### ISSUE THREAD

**Issue by levskaya** [JuliaGL/GLVisualize.jl#29]
Hi, it seems that "slerp" is undefined in function cubecamera in camera.jl:102 in master.

I can't seem to find any package that might supply this function either.  This is causing import with "using GLPlot" to fail for me on v0.4 os x.

Thanks!

**Comment by SimonDanisch** [comment]
Hi, sorry about that... GLPlot is not quite ready yet.
I opened a PR to fix this: https://github.com/forio/Quaternions.jl/pull/6

Best,
Simon
