### ISSUE TITLE
Howto add colors and shape in nbody.jl test example

### ISSUE THREAD

**Issue by AlainLich** [JuliaGL/GLVisualize.jl#3]
Hi Simon,

I am wondering how I can have different specified colors and/or shapes for the planets in example
nbody.jl.

In the variant that I use (subscreen6.xml) of Romeo/test, the code says
```
    const positions     = lift(send_frame, time_i, Input(world.planets))
    const robj          = visualize(positions, model=scalematrix(Vec3(0.1f0)),
                                    screen=sc, camera=cam)
```

Best 
Alain

PS: please let me know when I can try the **edit** object.

**Comment by SimonDanisch** [comment]
Hi,
off the top of my head, something like this should work:
```Julia
visualize(positions, primitive=GLNormalMesh(your_custom_mesh),
particle_color=rgba(1,0,1,1))
```
You can look at the results of `GLVisualize.visualize_default(positions,
Style{}())` (I need to give this a nicer interface and export it), to see
what defaults it uses ( to then give it customized attributes).

You might want to create something like `call{M <: Mesh}(::Type{M}, Sphere)
= M(sphere_vertex, sphere_faces)`

I'll hope to finish my bachelor thesis in the next days... After that I'll
use 100% of my time to develop the edit widgets ;)

Best,
Simon

2015-05-27 15:18 GMT+02:00 AlainLich <notifications@github.com>:

**Comment by AlainLich** [comment]
Hi

I understand you are busy, so I will not bug you for a fortnight. 

I'll try to use your suggestions. The problem is that in this example there are 4  planets, so I suppose I need to separate them and issue separate visualize for each (with proper color and style), in the same spirit as what is done to display the trajectories.

Best
Alain

**Comment by SimonDanisch** [comment]
aaah okay wait let me look into it ;)

2015-05-27 17:00 GMT+02:00 AlainLich <notifications@github.com>:

**Comment by SimonDanisch** [comment]
Okay, try it out... you need to update GLAbstraction and GLVisualize.
(Example in test_particles.jl)
Best,
Simon

**Comment by AlainLich** [comment]
Thanks

**Comment by AlainLich** [comment]
Hi Simon,

got it to run, also needed to update Reactive. **I'll let you write your thesis from now on.**

Best 
Alain

PS: FYI, I made some progress with extending MetadataTools to display installed packages 
`https://github.com/AlainLich/MetadataTools.jl/tree/supportInstalled`. For Romeo (including GLAbstraction), this gives the following graph

![tp2_romeo](https://cloud.githubusercontent.com/assets/11294498/7854838/418c1b68-051d-11e5-9645-ffd9531dd3f7.jpg)
(*This needs several patches notably to Graphs, corresponding PRs not merged yet*)
