### ISSUE TITLE
Antialiasing

### ISSUE THREAD

**Issue by StreetLevel** [JuliaGL/GLVisualize.jl#4]
Hi Simon,

First thank you again for your great help!
Now i got one last question: Is there an option to turn on antialiasing?

greetings max

**Comment by SimonDanisch** [comment]
Anti-aliasing is sadly a little bit problematic, as I have a mixture of different anti-aliasing models and some extra render targets for 3D picking.
I have a good fix for this, but its low on my current priority list, so its simply not implemented yet.
As a work around, you can do this though:
go to https://github.com/JuliaGL/GLVisualize.jl/blob/master/src/display/renderloop.jl#L23
and change `(GLFW.SAMPLES,      0)` to something like `(GLFW.SAMPLES,      4)`

**Comment by SimonDanisch** [comment]
I added a prototype for anti aliasing in the the fsaa branch... But I guess it won't do much for the line rendering... I need to implement some better line rendering at some point

**Comment by SimonDanisch** [comment]
fixed on master!

**Comment by SimonDanisch** [comment]
Actually also tagged now ;)
