### ISSUE TITLE
Cannot precompile at the start of a new day

### ISSUE THREAD

**Issue by kleinash** [JuliaGL/GLVisualize.jl#41]
Somewhere between GLAbstraction and GLVisualize. GeometryTypes is not the issue because I have to remove both GLAbstraction and GLVisualize to build and run - today which is different to yesterday when everything was working just fine. 

`using MAT, GLVisualize, FileIO, Colors, GeometryTypes, GLAbstraction, PyPlot`

WARNING: could not import GeometryTypes.SimpleRectangle into GLAbstraction
ERROR: LoadError: LoadError: UndefVarError: SimpleRectangle not defined
 in include at ./boot.jl:261
 in include_from_node1 at ./loading.jl:304
 in include at ./boot.jl:261
 in include_from_node1 at ./loading.jl:304
 [inlined code] from none:2
 in anonymous at no file:0
 in process_options at ./client.jl:257
 in _start at ./client.jl:378
while loading /home/ashley/.julia/v0.4/GLAbstraction/src/AbstractGPUArray.jl, in expression starting on line 86
while loading /home/ashley/.julia/v0.4/GLAbstraction/src/GLAbstraction.jl, in expression starting on line 15
ERROR: LoadError: Failed to precompile GLAbstraction to /home/ashley/.julia/lib/v0.4/GLAbstraction.ji
 in error at ./error.jl:21
 in compilecache at loading.jl:384
 in require at ./loading.jl:250
 in include at ./boot.jl:261
 in include_from_node1 at ./loading.jl:304
 in process_options at ./client.jl:280
 in _start at ./client.jl:378

**Comment by SimonDanisch** [comment]
Sorry for this :-D you must have fetched at a very unlucky time!
Please do:

```JuliaPkg.checkout("Reactive")
Pkg.checkout("GLVisualize")
Pkg.checkout("GLAbstraction")
Pkg.checkout("GLWindow")
Pkg.checkout("GeometryTypes")
Pkg.checkout("Packing")
Pkg.checkout("FreeType")
```

**Comment by kleinash** [comment]
Message received :) All good.
