### ISSUE TITLE
bug in 2d lines

### ISSUE THREAD

**Issue by CarloLucibello** [JuliaGL/GLVisualize.jl#47]
I'm trying to plot a graph using GLVisualize, and I was trying to display an edge as a line, that is something like

```julia
w, r = glscreen()
@async r()

s = Vec2f0(50)
N = nv(g)
v_pos = Point2f0[Point2f0((N*s[1]*rand(2))...) for i=1:N]
v = visualize(v_pos[1:2], :lines, scale=s)
view(v, method=:orthographic_pixel)
```
but all I get is a blank window. I'm on `next2` branch

The same goes for `v = visualize(v_pos[1:3], :lines, scale=s)` while for 4 or more the piecewise line is displayed correctly.

PS
I tried to `view` a `LineSegment` from GeometryTypes but it didn't worked out

PPS
I've in mind to write something like
```julia

function plot(g::SimpleGraph)
    srand(17)
    w, r = glscreen()
    @async r()

    s = Vec2f0(50)
    N = nv(g)
    v_pos = Point2f0[Point2f0((N*s[1]*rand(2))...) for i=1:N]
    v_img = HyperSphere(Point2f0(0), 30f0)
    vis_nodes = visualize((v_img, v_pos), :lines, scale=s)
    view(vis_nodes, method=:orthographic_pixel)

    for e in edges(g)
        epos = [v_pos[src(e)], v_pos[dst(e)]]
        v = visualize(epos, :lines, scale=s)
        view(v, method=:orthographic_pixel)
    end
end
```
Since I'm new to GLVisualize (and to graphics in general)  probably I"m doing it wrong, any suggestion is appreciated

**Comment by SimonDanisch** [comment]
Is N very big? Because then the points would be outside the window area...

**Comment by CarloLucibello** [comment]
It is small, N=10

Defining this function
```julia
function plot(m)
    srand(17)
    w, r = glscreen()
    @async r()
    s = Vec2f0(50)
    N = 10
    v_pos = Point2f0[Point2f0((N*s[1]*rand(2))...) for i=1:N]
    v_img = HyperSphere(Point2f0(0), 30f0)
    vis_nodes = visualize((v_img, v_pos), :lines, scale=s)
    view(vis_nodes, method=:orthographic_pixel)

    # m used here
    v = visualize(v_pos[1:m], :lines, scale=s)

    view(v, method=:orthographic_pixel)
end
```
I obtain

`plot(5)`
![glvisualize_005](https://cloud.githubusercontent.com/assets/7014210/11777780/cfc2c924-a250-11e5-87a4-27ae23774b02.png)

`plot(4)`
![glvisualize_007](https://cloud.githubusercontent.com/assets/7014210/11777788/d8b43af4-a250-11e5-85cf-7b9c4a9a03ab.png)

`plot(3)`
![glvisualize_008](https://cloud.githubusercontent.com/assets/7014210/11777813/f20ea41c-a250-11e5-9d1e-0f066f830b27.png)

**Comment by SimonDanisch** [comment]
I guess your problem is that the primitives are not centered?
I should have fixed this in a newer commit, if you dare to checkout.
Also, when given a primitive with dimensions, you don't need to supply the scale!
In the newer commit, you can define the centering yourself. With the circle, it's centered at the middle point.

**Comment by CarloLucibello** [comment]
Oh yes, that was a problem, but the real problem is that with plot(3) I was expecting to see two segments

**Comment by SimonDanisch** [comment]
Ah yeah... That's actually what I wanted to work on today. That's a peculiarity of OpenGL and I want to make a proper work around and fix another issue while at it (being able to add a list of indexes and specifying which points are connected). The only work around you can use right away is, to never have less than 4 points...
There is this annoying temporary fix:
```Julia
a,b = points 
ab = b-a
points = vcat(a-(ab*0.00001f0),a,b,b+(ab*0.00001f0)) #start and end have to be slightly different
```

**Comment by CarloLucibello** [comment]
ok thanks.

As an alternative, there is a way to visualize types from GeometryTypes.jl, like LineSegment?

**Comment by CarloLucibello** [comment]
>(being able to add a list of indexes and specifying which points are connected).

that's exactly what I need to visualize a graph

**Comment by SimonDanisch** [comment]
Well, that's basically what I will be implementing.

**Comment by SimonDanisch** [comment]
Great! I can't promise anything, but I'm working on it ;)

**Comment by SimonDanisch** [comment]
Okay I fixed the line endings and made a step forward towards the segments ;) I just need to integrate a few changes into the rest of the infrastructure to make it work for the generic case.

**Comment by CarloLucibello** [comment]
nice!

still some sprites' offset after last patches
![glvisualize_001](https://cloud.githubusercontent.com/assets/7014210/11796601/3f2f84f2-a2bd-11e5-8414-f1206562caae.png)

**Comment by SimonDanisch** [comment]
uh...have you removed `scale=s` ?

**Comment by CarloLucibello** [comment]
ouch, right, sorry, it works perfectly!

**Comment by mmoh** [comment]
@SimonDanisch 
Any idea why I keep getting this?
`julia
julia> Pkg.checkout("GeometryTypes", "sd/typealias")
INFO: Checking out GeometryTypes sd/typealias...
WARNING: Cannot perform fast-forward merge.
INFO: Pulling GeometryTypes latest sd/typealias...
WARNING: Cannot perform fast-forward merge.
INFO: No packages to install, update or remove
`

**Comment by SimonDanisch** [comment]
that's a julia/github issue. Sometimes it helped to first do `Pkg.checkout("GeometryTypes", "master")`.
You can also try doing it manually. Just go into the `GeometryTypes` folder with your terminal and type:
```Julia
git checkout sd/typealias
```
You might need to throw in a:
```Julia
git reset --hard HEAD
```
If there have been changes in the sources.
