### ISSUE TITLE
Animation?

### ISSUE THREAD

**Issue by dlfivefifty** [JuliaGL/GLVisualize.jl#50]
I wanted to get animation working, where the data of a plot is updated.  I tried this:

```julia
xv, yv = collect(Float32, 1:n), collect(Float32, 1:n)
x=Signal(xv*ones(yv)')
y=Signal(ones(xv)*yv')

z=Signal(map((x,y)->exp(x)*cos(y),x.value,y.value))

viz = visualize(x, y, z, Style(:surface))
```

But it errors outs since `visualize_defaults` is not defined.

**Comment by SimonDanisch** [comment]
That code hasn't seen any love in a long time :D In `next2` it looks quite a bit better. I fixed your example in the newest commit!

```Julia
n = 100
xv, yv = collect(Float32, 1:n), collect(Float32, 1:n)
x=Signal(xv*ones(yv)')
y=Signal(ones(xv)*yv')

z= map((x,y)->exp(x)*cos(y),x,y)
# or
# z= map((x,y)->map((x,y)-> exp(x)*cos(y), x,y),x,y)
# or
# x=Signal(xv*ones(yv)')
# y=Signal(ones(xv)*yv')
# map(i->map((x,y) -> exp(x)*cos(y)) ,loop(1:10))


viz = visualize(x, y, z, :surface)
```

**Comment by SimonDanisch** [comment]
You need to do something about the Inf32, though ... And maybe scale things a bit! Either the data, or via `visualize(x,y,z, :suface, model=scalematrix(Vec3f0(0.003)))`

**Comment by dlfivefifty** [comment]
Sorry, the example was silly: it should be plotted for x=y=0.:.1:1.

**Comment by SimonDanisch** [comment]
Is this solved?
