### ISSUE TITLE
Running example rotate_robj.jl

### ISSUE THREAD

**Issue by kleinash** [JuliaGL/GLVisualize.jl#53]
Hi,

Run into an error when running rotate_robj.jl out of the box:

:~/GIT/grasp_convnet/src/input_data/GLVisualize.jl/examples$ julia rotate_robj.jl 
WARNING: Method definition hash(GLFW.Window, UInt64) in module GLFW at ~/.julia/v0.4/GLFW/src/glfw3.jl:277 overwritten in module GLWindow at ~/.julia/v0.4/GLWindow/src/reactglfw.jl:217.
WARNING: Method definition ==(GLFW.Window, GLFW.Window) in module GLFW at ~/.julia/v0.4/GLFW/src/glfw3.jl:274 overwritten in module GLWindow at ~/.julia/v0.4/GLWindow/src/reactglfw.jl:219.
WARNING: MethodError(.+,((FixedSizeArrays.Point{3,Float32}((0.0f0,0.0f0,0.0f0)),FixedSizeArrays.Point{3,Float32}((0.0f0,0.0f0,0.0f0)),FixedSizeArrays.Point{3,Float32}((0.0f0,0.0f0,0.0f0))),FixedSizeArrays.Point{3,Float32}((2.9272021f-5,5.625886f-5,-6.0645714f-5))))
 in normals at ~/.julia/v0.4/GeometryTypes/src/algorithms.jl:9
 in normals at ~/.julia/v0.4/GeometryTypes/src/algorithms.jl:3
 in load at ~/.julia/v0.4/MeshIO/src/io/obj.jl:52
 in anonymous at ~/.julia/v0.4/MeshIO/src/MeshIO.jl:16
 in open at iostream.jl:114
 in load at ~/.julia/v0.4/MeshIO/src/MeshIO.jl:14 (repeats 2 times)
 in load at ~/.julia/v0.4/FileIO/src/loadsave.jl:77
 in load at ~/.julia/v0.4/FileIO/src/loadsave.jl:42
 in include at ./boot.jl:261
 in include_from_node1 at ./loading.jl:304
 in process_options at ./client.jl:280
 in _start at ./client.jl:378
ERROR: LoadError: MethodError: `.+` has no method matching .+(::Tuple{FixedSizeArrays.Point{3,Float32},FixedSizeArrays.Point{3,Float32},FixedSizeArrays.Point{3,Float32}}, ::FixedSizeArrays.Point{3,Float32})
Closest candidates are:
  .+{T<:FixedSizeArrays.FixedArray{T,NDim,SIZE}}(!Matched::T<:FixedSizeArrays.FixedArray{T,NDim,SIZE}, ::T<:FixedSizeArrays.FixedArray{T,NDim,SIZE})
  .+{T1<:FixedSizeArrays.FixedArray{T,NDim,SIZE},T2<:FixedSizeArrays.FixedArray{T,NDim,SIZE}}(!Matched::T1<:FixedSizeArrays.FixedArray{T,NDim,SIZE}, ::T2<:FixedSizeArrays.FixedArray{T,NDim,SIZE})
  .+{T<:Number}(!Matched::T<:Number, ::FixedSizeArrays.FixedArray{T<:Number,NDim,SIZE})
  ...
while loading ~/GLVisualize.jl/examples/rotate_robj.jl, in expression starting on line 5

**Comment by SimonDanisch** [comment]
Oh, maybe try `Pkg.checkout("MeshIO")`

**Comment by kleinash** [comment]
Nope - same error.. I am in branch sd/screenbuffer for GLVisualize and master for MeshIO. Could that be the issue?

**Comment by SimonDanisch** [comment]
Yes, that's a problem since it's outdated.
