### ISSUE TITLE
Bad text rendering on ubuntu

### ISSUE THREAD

**Issue by SimonDanisch** [JuliaGL/GLVisualize.jl#6]
I can confirm now, what @AlainLich mentioned regarding the text rendering.
It looks absolutely terrible on my ubuntu pc and the alignment is all mixed up :D
As my code is not really platform dependent, I argue that this must be an inconsistency in Cairo+FreeType. I'll investigate!

**Comment by sjkelly** [comment]
Confirmed here?

![glvis_text_bug](https://cloud.githubusercontent.com/assets/2086412/7926046/1f61da00-0892-11e5-809a-e0c045e4c9ab.png)

**Comment by SimonDanisch** [comment]
Yup, exactly the same look! At least it seems to be consistent ;)

**Comment by SimonDanisch** [comment]
This is kinda fixed by the way.... I'm just trying to build a better test suite, before I merge the fix ;)
