### ISSUE TITLE
Enhancement: Add a special exception if TIMER_SIGNAL is not defined

### ISSUE THREAD

**Issue by rapus95** [JuliaGL/GLVisualize.jl#61]
consider to catch the `TIMER_SIGNAL not found` and tell the user that he must call `glscreen()` first

(-> You don't need an open window but explicitly must call that special function what means you can't create the window by GLFW and use it here)

**Comment by SimonDanisch** [comment]
>You don't need an open window but explicitly must call that special function what means you can't create the window by GLFW and use it here

Well, that's in part, because a lot of stuff won't work than... But I agree, in general this is really bad design ;)
Making this all more independant might just be my next project...
