### ISSUE TITLE
ERROR: 0:40: Unknown identifier 'depth_greater' in layout

### ISSUE THREAD

**Issue by ssfrr** [JuliaGL/GLVisualize.jl#66]
I ran into the title error running the tests for GLVisualize. My guess is the underlying problem is the warning printed right before the error:

```
WARNING: 0:3: extension 'GL_ARB_conservative_depth' is not supported
ERROR: 0:40: Unknown identifier 'depth_greater' in layout
```

This is running on OSX 10.10.5 on a 2011 Macbook Air with Intel HD Graphics 3000. [this site](http://feedback.wildfiregames.com/report/opengl/feature/GL_ARB_conservative_depth) suggests my graphics card doesn't support this extension. Is it necessary for the examples to work correctly?

Full output is at https://gist.github.com/ssfrr/f129b321317aa5a735b2

**Comment by SimonDanisch** [comment]
I haven't tagged the fix for this yet:
https://github.com/JuliaGL/GLVisualize.jl/issues/62
fixed by: https://github.com/JuliaGL/GLVisualize.jl/pull/64
So a `Pkg.checkout("GLVisualize")` should do the trick!

**Comment by ssfrr** [comment]
Ah, whoops. I only looked in open issues. Sorry for the dup. Thanks!

**Comment by SimonDanisch** [comment]
No problem :)
