### ISSUE TITLE
add icon and methods to change title and icon.

### ISSUE THREAD

**Issue by musm** [JuliaGL/GLVisualize.jl#71]
It would be nice if we had a little icon for the GLVisualize window.

Also it wouldn't be a bad idea to include some ways to change the window name and icon for future application development using GLVisualize.

![image](https://cloud.githubusercontent.com/assets/4319522/13608829/6e690528-e524-11e5-8d32-00f12cbb3ff3.png)

Thanks

**Comment by SimonDanisch** [comment]
You can change the title with:
```
window = glscreen("My Title")
```
I'll look into the window icon!

**Comment by SimonDanisch** [comment]
Ugh: http://www.glfw.org/docs/latest/group__window.html#ga5c336fddf2cbb5b92f65f10fb6043344
Under remarks it states, that icons only fully work on windows...

**Comment by musmo** [comment]
Maybe first we can add them for Windows then wait for a fix from them?

**Comment by SimonDanisch** [comment]
seems like the situation has changed:
http://www.glfw.org/docs/latest/group__window.html#gadd7ccd39fe7a7d1f0904666ae5932dc5
:)

**Comment by musm** [comment]
awsome! Does GLVisualize have a logo or we can just default to the Julia logo for simplicity.

**Comment by SimonDanisch** [comment]
Good question! Maybe its time for a GLVisualize logo! :)

**Comment by LeMinaw** [comment]
This discussion is old, but I too find this little lack a shame :p
GLVisualize is amazing, it totally deserves a logo!
If you're interested, we can figure it out together. :)

**Comment by SimonDanisch** [comment]
Ah, completely forgot about this... I've just done the first step:
https://github.com/JuliaGL/GLFW.jl/pull/143
Now, for the logo... I think I currently don't have time for designing a nice one, and probably by now I'd rather have a nice icon for [Makie](https://github.com/JuliaPlots/Makie.jl)
