### ISSUE TITLE
remove rendered object

### ISSUE THREAD

**Issue by CarloLucibello** [JuliaGL/GLVisualize.jl#72]
Since there is no example for this in the documentation, I'll ask here. How can I signal and implement the removal of one of the rendered object?

In my use case, for https://github.com/JuliaGraphs/GraphVisualize.jl, I'd like to signal the removal of an edge from a graph, therefore removing one of the segmente created by
```julia
lines  = visualize(gpu_position, :linesegment, indices=indices)
```

Can you point me to some way to do this?
thanks

**Comment by SimonDanisch** [comment]
The easiest seems to be, if you just pass an index list to the points as well and then just remove indices.
I updated the example! At some point it was possible to use `splice!` on the gpu array directly, but this currently introduces some complications.

**Comment by SimonDanisch** [comment]
5ab7bb067425dc69798ad3103ecd0f71f843fd03

**Comment by CarloLucibello** [comment]
ok thanks
