### ISSUE TITLE
Drawing lines that are not connected

### ISSUE THREAD

**Issue by StreetLevel** [JuliaGL/GLVisualize.jl#75]
Hi Simon,

lot has changed since i took a look at glvisualize last time.
Like the last time i've opened a issue here (Issue #1) i want to draw a mesh from a list of faces and vertices and in addition the edges of the faces.
It is a lot easier now to do the first part:
`vertices = Point3f0[...some vertices]
faces = Face{3,UInt32,0}[...some faces]
...
mesh = GLNormalAttributeMesh(
    vertices=vertices, faces=faces,
    attributes=colors, attribute_id=color_ids
) #create the mesh
view(visualize(mesh), window) #visualize
...
`
For the second part i've not found a clean solution by now.
if i do this from the example:
`lines = visualize(
	positions, :linesegment, thickness=0.5f0,
	color=color, indices=indices, model=rotation
)`
I only get connected lines. I think calling the visualize routine like tenthousand times is not an option... What i want is to draw several not connected lines at one time. 
Is there a possibility to do so? 
Nice would be a Array{Int32,2}-index vector in the example above or a mesh where i can pass
Face{2,UInt32,0}-entities.

Thank you in advance.

And by the way: glVisualize is really good work. The options we got with reactive are amazing. I saw your presentation at JuliaCom: SPIR-V and Hypersignals are looking really promising. If you get these projects to work you really would solve many of our problems, so good luck for that!

Best, Max

**Comment by SimonDanisch** [comment]
Hi Max,
thanks a lot :)

>lines = visualize( positions, :linesegment, thickness=0.5f0, color=color, indices=indices, model=rotation )
I only get connected lines

That surprises me, it shouldn't be the case! Are you sure, that you don't accidantly actually connect them yourself via the indices?
Indices need to look like this:
```Julia
1.____ 2.         3.____.4
inds = [1,2, 3,4] # <- with Int as type it will get converted to 0 indexed automatically
# or 0 indexed with no conversion (differentiated via the the type, which will change)
inds = Cuint[0,1, 2,3]
```

>Nice would be a Array{Int32,2}-index vector in the example above or a mesh where i can pass
Face{2,UInt32,0}-entities.


I'm thinking about how to solve this nicely in general at the moment, discussion will be at: https://github.com/JuliaGeometry/GeometryTypes.jl/issues/46

Though I haven't really talked about indexed arrays there (yet) ;)

**Comment by StreetLevel** [comment]
hey simon,
thank you for your immediate answear.
I've tried to write a minimal working example:
```julia
using GLAbstraction, Colors, GeometryTypes, GLVisualize

if !isdefined(:runtests)
    window = glscreen()
end

xyz    = Point3f0[Point3f0(0.), Point3f0(100.,0.,0.), Point3f0(0.,10.,0.), Point3f0(100.,10.,0.), Point3f0(0.,20.,0.), Point3f0(100.,20.,0.)]
inds = UInt32[1,2,3,4,5,6]
colors = RGBA{U8}[RGBA{U8}(rand(), rand(), rand(), 1.0) for i=1:6]

lines = visualize(
	xyz, :linesegment, thickness = 1.5f0,
	color = colors, indices = inds
)

view(lines, window, camera=:perspective)

if !isdefined(:runtests)
	renderloop(window)
end
```
I hoped to see three different parallel lines. But there is only one line.
What am i doing wrong?

Best, Max

**Comment by SimonDanisch** [comment]
Okay, that's a sneeky problem, sorry about that!
It needs to be:
```Julia
# RGBA{U8} is currently not supported for lines, you need to use Float32!
colors = RGBA{Float32}[RGBA{Float32}(rand(), rand(), rand(), 1.0) for i=1:6]
# either 1 indexed with type Int
inds = Int[1,2,3,4,5,6]
# or 0 indexed with type Cuint
inds = UInt32[0,1,2,3,4,5]
# By the way, you don't need to supply indexes if they are a linear range....
```

**Comment by StreetLevel** [comment]
works like a charm...thank you very much.
me and my coworker r.l. gates (i think you know him) are trying to write a n>3-dimensional FEM-Engine with hierarchical adaptive mesh refinment at the moment. I think glVisualize in combination with reactive is a nice tool to update the plot automatically if some elements are refined. We maybe want to plot space-time meshes so the possibilities of interaction of glvisualize with the sliders, etc seems to be a perfect fit. I will working on the visualization of the meshes in the next few weeks beneath work, so it would be nice if i can ask you one or two additional question if you are available.

Thank you in advance & Greeting from Hannover.

Best, Max

**Comment by SimonDanisch** [comment]
Great! Looking forward to seeing it. Keep me updated on it, I'll help wherever I can!
Greetings from Berlin ;)

**Comment by SimonDanisch** [comment]
By the way, I've added a vertexcolor mesh type, which should be more fitting for what you're trying to do!
You need to be on GLVisualize, GLAbstraction and GeometryType master for that!
commit https://github.com/JuliaGL/GLVisualize.jl/commit/a69765daf9dbc5cbae5cbc698646e6793ad90261
