### ISSUE TITLE
How do you clear plots?

### ISSUE THREAD

**Issue by dlfivefifty** [JuliaGL/GLVisualize.jl#88]

**Comment by SimonDanisch** [comment]
`empty!(w)` (empties the renderlist) and maybe also a `clear_all!(w)` [clears the screen](https://github.com/JuliaGL/GLWindow.jl/blob/master/src/render.jl#L1)

**Comment by dlfivefifty** [comment]
Thanks!  Can you add this to the documentation?

I’m also getting unexplained white bands for contour plots.  I’ll try to come up with a simple example.

**Comment by SimonDanisch** [comment]
you mean something like this:
![image](https://cloud.githubusercontent.com/assets/1010467/14568856/b9eade60-033b-11e6-9f63-bf2c7ded4ba1.png)
