### ISSUE TITLE
Syntax change

### ISSUE THREAD

**Issue by kleinash** [JuliaGL/GLVisualize.jl#90]
Hi,

I probably shouldnt have updated, but I am now getting a build error:

```julia
ERROR: LoadError: LoadError: UndefVarError: renderlist not defined
 in include at ./boot.jl:261
 in include_from_node1 at ./loading.jl:320
 in include at ./boot.jl:261
 in include_from_node1 at ./loading.jl:320
 [inlined code] from none:2
 in anonymous at no file:0
 in process_options at ./client.jl:257
 in _start at ./client.jl:378
while loading .julia/v0.4/GLWindow/src/screen.jl, in expression starting on line 433
while loading .julia/v0.4/GLWindow/src/GLWindow.jl, in expression starting on line 29
ERROR: LoadError: Failed to precompile GLWindow to .julia/lib/v0.4/GLWindow.ji
```

Thx

**Comment by SimonDanisch** [comment]
Are you on master, or the newest tagged version? Is any repo dirty, so that `Pkg.update()` didn't update all packages?

**Comment by kleinash** [comment]
yes on master - nothing is dirty (having checked with git status.

**Comment by SimonDanisch** [comment]
are you on GLAbstraction master as well?

**Comment by kleinash** [comment]
Yes

**Comment by SimonDanisch** [comment]
huh... Seems there was one commit missing.. Can you pull GLAbstraction again?

**Comment by kleinash** [comment]
Yup that did it - seems a lot slower though.. Thanks. :+1:

**Comment by SimonDanisch** [comment]
What exactly feels a lot slower? Can you also checkout GLWindow and GLVisualize and see if it still feels a lot slower?

**Comment by kleinash** [comment]
Before it spawns the window for the first time, and then the window goes black and that wait really does seem longer. But right now I am not getting out the right picture. #89 which is my triage area.
