### ISSUE TITLE
Segmentation faults and screen freezes

### ISSUE THREAD

**Issue by jhlq** [JuliaGL/GLVisualize.jl#91]
Have had to hard reset three times now from trying out the examples, the most recent one was linesegments3d (with reduced amount of lines), mouse still movable but nothing responds.

The other two were caused by unmodified examples, IIRC the lines3D and camera scripts (in one case the mouse also locked down). 

8 core i7 with GeForce GTX 760 and 8GB RAM running julia 4.5 in Ubuntu 15.

julia> Pkg.test("GLVisualize")
INFO: Computing test dependencies for GLVisualize...
INFO: Cloning cache of FactCheck from git://github.com/JuliaLang/FactCheck.jl.git
INFO: Installing FactCheck v0.4.2
INFO: Testing GLVisualize
Image Like
  > viewable creation
    > viewing
0 facts verified.
sprite particles
  > on a 2D plane
    > viewable creation
      > viewing
  > in 3D space
    > viewable creation
      > viewing
0 facts verified.
Surfaces
  > viewable creation
    > viewing
0 facts verified.
Lines
  > viewable creation
    > viewing
0 facts verified.

signal (11): Segmentation fault
unknown function (ip: 0x7fbfb05cf7cc)
unknown function (ip: 0x7fbfb05cfbdb)
unknown function (ip: 0x7fbfb053cd48)
unknown function (ip: 0x7fbfb05cd4a2)
unknown function (ip: 0x7fbfb058c7ce)
unknown function (ip: 0x7fbfb058cb15)
unknown function (ip: 0x7fbfb053214c)
unknown function (ip: 0x7fbfb05eb4d4)
unknown function (ip: 0x7fbfb05f1dea)
unknown function (ip: 0x7fbfb05f8d2e)
unknown function (ip: 0x7fbfb060365e)
unknown function (ip: 0x7fbfb02ddbdf)
unknown function (ip: 0x7fbfb02afb68)
unknown function (ip: 0x7fbfb02afbf5)
glDrawElementsInstanced at /home/nicol/.julia/v0.4/ModernGL/src/functionloading.jl:39
renderinstanced at /home/nicol/.julia/v0.4/GLAbstraction/src/GLRender.jl:112
jlcall_renderinstanced_26395 at  (unknown line)
jl_apply_generic at /usr/bin/../lib/x86_64-linux-gnu/julia/libjulia.so (unknown line)
call at /home/nicol/.julia/v0.4/GLAbstraction/src/GLRenderObject.jl:56
jlcall_call_26394 at  (unknown line)
jl_apply_generic at /usr/bin/../lib/x86_64-linux-gnu/julia/libjulia.so (unknown line)
render at /home/nicol/.julia/v0.4/GLAbstraction/src/GLRender.jl:41
render at /home/nicol/.julia/v0.4/GLAbstraction/src/GLRender.jl:11
jlcall_render_26354 at  (unknown line)
jl_apply_generic at /usr/bin/../lib/x86_64-linux-gnu/julia/libjulia.so (unknown line)
render at /home/nicol/.julia/v0.4/GLWindow/src/render.jl:83
render at /home/nicol/.julia/v0.4/GLWindow/src/render.jl:85
render_frame at /home/nicol/.julia/v0.4/GLWindow/src/render.jl:24
renderloop at /home/nicol/.julia/v0.4/GLWindow/src/render.jl:45
jlcall_renderloop_26331 at  (unknown line)
jl_apply_generic at /usr/bin/../lib/x86_64-linux-gnu/julia/libjulia.so (unknown line)
unknown function (ip: 0x7fc1cfdaca43)
unknown function (ip: 0x7fc1cfdabdbb)
unknown function (ip: 0x7fc1cfdad2ad)
unknown function (ip: 0x7fc1cfdad5d6)
unknown function (ip: 0x7fc1cfdc2077)
unknown function (ip: 0x7fc1cfdc296c)
jl_load at /usr/bin/../lib/x86_64-linux-gnu/julia/libjulia.so (unknown line)
include at ./boot.jl:261
jl_apply_generic at /usr/bin/../lib/x86_64-linux-gnu/julia/libjulia.so (unknown line)
include_from_node1 at ./loading.jl:320
jl_apply_generic at /usr/bin/../lib/x86_64-linux-gnu/julia/libjulia.so (unknown line)
process_options at ./client.jl:284
_start at ./client.jl:378
unknown function (ip: 0x7fc1cc7e53d9)
jl_apply_generic at /usr/bin/../lib/x86_64-linux-gnu/julia/libjulia.so (unknown line)
unknown function (ip: 0x401b87)
unknown function (ip: 0x40174f)
__libc_start_main at /lib/x86_64-linux-gnu/libc.so.6 (unknown line)
unknown function (ip: 0x401799)
unknown function (ip: (nil))
=============================[ ERROR: GLVisualize ]=============================

failed process: Process(`/usr/bin/julia --check-bounds=yes --code-coverage=none --color=yes /home/nicol/.julia/v0.4/GLVisualize/test/runtests.jl`, ProcessSignaled(11)) [0]

================================================================================
INFO: Removing FactCheck v0.4.2
ERROR: GLVisualize had test errors
 in error at ./error.jl:21
 in test at pkg/entry.jl:803
 in anonymous at pkg/dir.jl:31
 in cd at file.jl:22
 in cd at pkg/dir.jl:31
 in test at pkg.jl:71

**Comment by SimonDanisch** [comment]
Okay that looks bad! :( Are you on the newest version of GLVisualize?

**Comment by SimonDanisch** [comment]
Can you do:
```Julia
Pkg.checkout("GLAbstraction", "sd/bugfix")
```
and then try the test again?

**Comment by jhlq** [comment]
Same error after Pkg.checkout("GLAbstraction", "sd/bugfix") and Pkg.checkout("GLVisualize")

**Comment by SimonDanisch** [comment]
Would have been too easy...What driver did you install?

**Comment by SimonDanisch** [comment]
What does
```
glxinfo | grep 'version'
```
report?
You might need `sudo apt-get install mesa-utils`

**Comment by jhlq** [comment]
Possibly only the ones preinstalled, perhaps installing "NVIDIA binary driver - version 340.96" can help?

server glx version string: 1.4
client glx version string: 1.4
GLX version: 1.4
OpenGL core profile version string: 4.1 (Core Profile) Mesa 11.0.2
OpenGL core profile shading language version string: 4.10
OpenGL version string: 3.0 Mesa 11.0.2
OpenGL shading language version string: 1.30
OpenGL ES profile version string: OpenGL ES 3.0 Mesa 11.0.2
OpenGL ES profile shading language version string: OpenGL ES GLSL ES 3.00

**Comment by SimonDanisch** [comment]
Okay that looks good...

**Comment by SimonDanisch** [comment]
Sorry for the hassle...
Can you also try:
```Julia
Pkg.checkout("ModernGL", "sd/bugfix")
Pkg.test("GLVisualize")
```
That's not a fix, but hopefully a better error message.

**Comment by jhlq** [comment]
Installing the latest drivers appears to have resolved the issue.
INFO: GLVisualize tests passed

Sorry for the hassle ^.^

**Comment by SimonDanisch** [comment]
Okay happy to hear... Still a bit worrisome, though :D

**Comment by jhlq** [comment]
A notice that people should ensure tests pass before playing around could help avoid loss of unsaved data from screen freezing
