### ISSUE TITLE
GLX_ARB_create_context_profile is unavailable

### ISSUE THREAD

**Issue by ultradian** [JuliaGL/GLVisualize.jl#92]
Hi,
I am an OpenGL newbie, trying to set up GLVisualize (and GLWindow) on a couple of Debian computers running Julia Version 0.4.3.  Unfortunately, as soon as I try to create a window I get the error:

```
ERROR: LoadError: GLX: Forward compatibility requested but GLX_ARB_create_context_profile is unavailable
 in error at ./error.jl:21
 in anonymous at /home/bla/.julia/v0.4/GLFW/src/GLFW.jl:26
 in ##ErrorCallbackWrapper#7019 at /home/bla/.julia/v0.4/GLFW/src/callback.jl:50
 in CreateWindow at /home/bla/.julia/v0.4/GLFW/src/glfw3.jl:342
snip
```

Relevant info:

```
client glx vendor string: Mesa Project and SGI
client glx version string: 1.4
including the GLX_ARB_create_context_profile extension
OpenGL vendor string: VMware, Inc.
OpenGL renderer string: Gallium 0.4 on llvmpipe (LLVM 3.5, 256 bits)
OpenGL version string: 3.0 Mesa 10.3.2
OpenGL shading language version string: 1.30
OpenGL context flags: (none)
```

From what I could tell at https://www.opengl.org/registry/specs/ARB/glx_create_context.txt
My version requires a GLX_ARB_create_context_profile to insure version compatibility, but I'm not sure why this isn't happening.  I tried checking out the master, but that didn't seem to help.  Any pointers or suggestions?

**Comment by SimonDanisch** [comment]
Hi,
that's most likely due to old drivers or an old gpu's... Can you try to update the driver and tell me your gpu?
Best,
Simon

**Comment by SimonDanisch** [comment]
Sorry, answered this from my smartphone and didn't see the full details.
```
OpenGL renderer string: Gallium 0.4 on llvmpipe (LLVM 3.5, 256 bits)
OpenGL version string: 3.0 Mesa 10.3.2
```
This means you're in software mode, which is really slow... Even if you're fine with that, GLVisualize needs OpenGL 3.3 ;)
Admittedly quite the high version, but I haven't had the resources to port code to older versions yet.
But most GPU's that are younger than 4 years should have at least OpenGL 3.3, if you update the drivers, or on Linux install the proprietary drivers. (`Gallium 0.4 on llvmpipe` suggests, that no driver is installed whatsoever).

**Comment by ultradian** [comment]
Thanks for the information.  I now have the nvidia driver 364.16 (which is supposed to support Vulkan) installed on my desktop.  GLVisualize works fine so far.  Of course, this doesn't help my laptop which has an intel integrated graphics chip, but I'm going to play around with it still....

**Comment by SimonDanisch** [comment]
Great :) Intel should be fine since hd 4000... 3000 is not supported... There should defintely be drivers for all of them :-D
